import { jest } from "@jest/globals";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import process from "node:process";

const spawnSyncMock = jest.fn();
jest.unstable_mockModule("node:child_process", () => ({
  spawnSync: spawnSyncMock,
}));

const { setUpDevelopmentEnvironment } =
  await import("../scripts/setUpDevelopmentEnvironment.js");
const platformDescriptor = Object.getOwnPropertyDescriptor(process, "platform");
const nodeVersionDescriptor = Object.getOwnPropertyDescriptor(
  process.versions,
  "node",
);

function createCommandResult(stdout = "", status = 0) {
  return {
    pid: 1,
    output: [null, stdout, ""],
    stdout,
    stderr: "",
    status,
    signal: null,
  };
}

// A pip-compile style lock: hashed pins, an extra marker, and comments.
const LOCK_TEXT = [
  "# autogenerated by pip-compile",
  "defusedxml==0.7.1 \\",
  "    --hash=sha256:aaaa",
  "    # via -r requirements.txt",
  "rdflib[html]==7.6.0 \\",
  "    --hash=sha256:bbbb \\",
  "    --hash=sha256:cccc",
  "jsonschema==4.26.0 \\",
  "    --hash=sha256:dddd",
  "# The following packages are considered to be unsafe in a requirements file:",
  "pip==26.2.1 \\",
  "    --hash=sha256:eeee",
  "",
].join("\n");
const INSTALLED_DISTRIBUTIONS = [
  { name: "defusedxml", version: "0.7.1" },
  { name: "rdflib", version: "7.6.0" },
  { name: "jsonschema", version: "4.26.0" },
  { name: "pip", version: "26.2.1" },
];

let temporaryDirectoryPath;
let repositoryRoot;
let npmCliPath;
let consoleLogSpy;

function getPythonVirtualEnvironmentExecutablePath() {
  return join(
    repositoryRoot,
    ".venv",
    ...(process.platform === "win32"
      ? ["Scripts", "python.exe"]
      : ["bin", "python"]),
  );
}

function createPythonVirtualEnvironmentFixture() {
  const executablePath = getPythonVirtualEnvironmentExecutablePath();
  mkdirSync(dirname(executablePath), { recursive: true });
  writeFileSync(executablePath, "existing interpreter");
}

beforeEach(() => {
  temporaryDirectoryPath = mkdtempSync(
    join(tmpdir(), "universal-ontology-development-"),
  );
  repositoryRoot = join(temporaryDirectoryPath, "checkout with spaces");
  mkdirSync(repositoryRoot);
  writeFileSync(
    join(repositoryRoot, "package.json"),
    JSON.stringify({ packageManager: "npm@12.0.2" }),
  );
  writeFileSync(join(repositoryRoot, "package-lock.json"), "{}");
  writeFileSync(join(repositoryRoot, ".node-version"), "24.20.0\n");
  writeFileSync(join(repositoryRoot, ".python-version"), "3.14.7\n");
  writeFileSync(
    join(repositoryRoot, "requirements-sdlc.txt"),
    "jsonschema==4.26.0\n",
  );
  Object.defineProperty(process.versions, "node", { value: "24.20.0" });
  writeFileSync(
    join(repositoryRoot, "requirements.txt"),
    "defusedxml>=0.7.1\n",
  );
  writeFileSync(join(repositoryRoot, "requirements.lock.txt"), LOCK_TEXT);
  npmCliPath = join(temporaryDirectoryPath, "npm cli.cjs");
  writeFileSync(npmCliPath, "");
  jest.replaceProperty(process, "env", {
    ...process.env,
    npm_execpath: npmCliPath,
  });
  consoleLogSpy = jest.spyOn(console, "log").mockImplementation(() => {});
  jest.spyOn(console, "warn").mockImplementation(() => {});

  // Package downloads and interpreter provisioning are the external boundary.
  // Directory inspection and preservation still use the real filesystem.
  spawnSyncMock
    .mockReset()
    .mockImplementation((executablePath, commandArguments) => {
      if (
        executablePath === process.execPath &&
        commandArguments[0] === npmCliPath
      ) {
        return createCommandResult(
          commandArguments[1] === "--version" ? "12.0.2\n" : "",
        );
      }
      if (executablePath === "aws") {
        return createCommandResult("aws-cli/2.30.0\n");
      }
      if (commandArguments[0] === "--version") {
        return createCommandResult("Python 3.14.7\n");
      }
      if (commandArguments[2] === "--version") {
        return createCommandResult("pip 26.2.1 from bootstrap (python 3.14)\n");
      }
      if (commandArguments[2] === "list") {
        return createCommandResult(JSON.stringify(INSTALLED_DISTRIBUTIONS));
      }
      if (commandArguments[0] === "-m" && commandArguments[1] === "venv") {
        createPythonVirtualEnvironmentFixture();
      }
      return createCommandResult();
    });
});

afterEach(() => {
  jest.restoreAllMocks();
  Object.defineProperty(process, "platform", platformDescriptor);
  Object.defineProperty(process.versions, "node", nodeVersionDescriptor);
  const cleanupPath = resolve(temporaryDirectoryPath);
  if (
    dirname(cleanupPath) !== resolve(tmpdir()) ||
    !basename(cleanupPath).startsWith("universal-ontology-development-")
  ) {
    throw new Error(
      "Refusing to remove a path outside the temporary fixtures.",
    );
  }
  rmSync(cleanupPath, { recursive: true, force: true });
});

test.each([
  ["win32", "python", "Scripts", "python.exe"],
  ["linux", "python3", "bin", "python"],
  ["darwin", "python3", "bin", "python"],
])(
  "installs locked npm and isolated Python dependencies on %s",
  (
    platform,
    systemPythonExecutableName,
    executableDirectory,
    executableName,
  ) => {
    Object.defineProperty(process, "platform", { value: platform });

    setUpDevelopmentEnvironment({ repositoryRoot });

    const commands = spawnSyncMock.mock.calls.map(
      ([executable, commandArguments]) => [executable, commandArguments],
    );
    const virtualEnvironmentPythonExecutablePath = join(
      repositoryRoot,
      ".venv",
      executableDirectory,
      executableName,
    );
    expect(commands).toEqual([
      [process.execPath, [npmCliPath, "--version"]],
      [systemPythonExecutableName, ["--version"]],
      [
        process.execPath,
        [npmCliPath, "ci", "--include=dev", "--ignore-scripts"],
      ],
      [
        systemPythonExecutableName,
        ["-m", "venv", join(repositoryRoot, ".venv")],
      ],
      [virtualEnvironmentPythonExecutablePath, ["-m", "pip", "--version"]],
      [
        virtualEnvironmentPythonExecutablePath,
        [
          "-m",
          "pip",
          "install",
          "--require-hashes",
          "--only-binary=:all:",
          "-r",
          join(repositoryRoot, "requirements.lock.txt"),
        ],
      ],
      [
        virtualEnvironmentPythonExecutablePath,
        ["-m", "pip", "list", "--format=json"],
      ],
      [virtualEnvironmentPythonExecutablePath, ["-m", "pip", "check"]],
      [
        virtualEnvironmentPythonExecutablePath,
        ["-B", join(repositoryRoot, "scripts", "set_up_sdlc.py")],
      ],
      ["aws", ["--version"]],
    ]);
    for (const [, , options] of spawnSyncMock.mock.calls) {
      expect(options.cwd).toBe(repositoryRoot);
      expect(options.shell).not.toBe(true);
      expect(options.windowsHide).toBe(true);
    }
    expect(existsSync(virtualEnvironmentPythonExecutablePath)).toBe(true);
    expect(consoleLogSpy).toHaveBeenCalledWith(
      expect.stringMatching(/Bootstrap pip: pip 26\.2\.1 from bootstrap/),
    );
  },
);

test("preserves an existing virtual environment and uses its interpreter", () => {
  createPythonVirtualEnvironmentFixture();
  const markerPath = join(repositoryRoot, ".venv", "user-owned-file.txt");
  writeFileSync(markerPath, "preserve this environment");

  setUpDevelopmentEnvironment({ repositoryRoot });

  expect(readFileSync(markerPath, "utf8")).toBe("preserve this environment");
  const pythonCommands = spawnSyncMock.mock.calls.filter(
    ([executable]) => executable !== process.execPath && executable !== "aws",
  );
  expect(pythonCommands.map(([executable]) => executable)).toEqual(
    Array(6).fill(getPythonVirtualEnvironmentExecutablePath()),
  );
  expect(
    pythonCommands.some(([, commandArguments]) =>
      commandArguments.includes("venv"),
    ),
  ).toBe(false);
});

test("rejects an unusable existing virtual environment before installation", () => {
  mkdirSync(join(repositoryRoot, ".venv"));
  writeFileSync(join(repositoryRoot, ".venv", "keep.txt"), "keep");

  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(
    /\.venv/,
  );
  expect(readFileSync(join(repositoryRoot, ".venv", "keep.txt"), "utf8")).toBe(
    "keep",
  );
  expect(spawnSyncMock.mock.calls.some(([, args]) => args.includes("ci"))).toBe(
    false,
  );
});

test.each([
  "package-lock.json",
  "requirements.txt",
  "requirements-sdlc.txt",
  "requirements.lock.txt",
  ".node-version",
  ".python-version",
])("rejects a missing %s before starting subprocesses", (filename) => {
  rmSync(join(repositoryRoot, filename));
  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(
    filename,
  );
  expect(spawnSyncMock).not.toHaveBeenCalled();
});

test("requires invocation through npm before changing the environment", () => {
  delete process.env.npm_execpath;
  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(
    /npm run setup:development/,
  );
  expect(spawnSyncMock).not.toHaveBeenCalled();
});

test("rejects a Node version below the documented prerequisite", () => {
  Object.defineProperty(process.versions, "node", { value: "22.0.0" });
  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(/Node/);
  expect(spawnSyncMock).not.toHaveBeenCalled();
});

test("rejects an npm version that differs from the packageManager declaration", () => {
  spawnSyncMock.mockReturnValueOnce(createCommandResult("11.0.0\n"));
  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(
    /npm@12\.0\.2/,
  );
  expect(spawnSyncMock.mock.calls.some(([, args]) => args.includes("ci"))).toBe(
    false,
  );
});

test.each([
  ["missing", { ...createCommandResult("", null), error: new Error("ENOENT") }],
  ["too old", createCommandResult("Python 3.10.0\n")],
  ["older patch than selected", createCommandResult("Python 3.14.6\n")],
])(
  "rejects %s Python before installing npm packages",
  (_description, result) => {
    const successfulCommand = spawnSyncMock.getMockImplementation();
    spawnSyncMock.mockImplementation((executable, args, options) =>
      args[0] === "--version"
        ? result
        : successfulCommand(executable, args, options),
    );
    expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(
      /Python/,
    );
    expect(
      spawnSyncMock.mock.calls.some(([, args]) => args.includes("ci")),
    ).toBe(false);
  },
);

test.each([
  ["npm installation", "ci"],
  ["virtual environment creation", "venv"],
  ["locked Python dependency installation", "--require-hashes"],
  ["pip consistency check", "check"],
  ["repository SDLC configuration", "-B"],
])("stops after a failed %s", (_description, failingArgument) => {
  const successfulCommand = spawnSyncMock.getMockImplementation();
  spawnSyncMock.mockImplementation((executable, args, options) =>
    args.includes(failingArgument)
      ? createCommandResult("", 7)
      : successfulCommand(executable, args, options),
  );

  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(/7/);
  expect(spawnSyncMock.mock.lastCall[1]).toContain(failingArgument);
});

test.each([
  [
    "a distribution version differing from the lock",
    INSTALLED_DISTRIBUTIONS.map((item) =>
      item.name === "rdflib" ? { name: "rdflib", version: "7.5.0" } : item,
    ),
    /rdflib.*7\.5\.0.*7\.6\.0/,
  ],
  [
    "an installed distribution absent from the lock",
    [...INSTALLED_DISTRIBUTIONS, { name: "PyShacl", version: "0.40.1" }],
    /pyshacl/,
  ],
  [
    "a locked distribution that is not installed",
    INSTALLED_DISTRIBUTIONS.filter(({ name }) => name !== "jsonschema"),
    /jsonschema/,
  ],
])(
  "refuses %s before repository SDLC configuration",
  (_description, installed, expected) => {
    const successfulCommand = spawnSyncMock.getMockImplementation();
    spawnSyncMock.mockImplementation((executable, args, options) =>
      args[2] === "list"
        ? createCommandResult(JSON.stringify(installed))
        : successfulCommand(executable, args, options),
    );

    expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(
      expected,
    );
    expect(
      spawnSyncMock.mock.calls.some(([, args]) => args.includes("check")),
    ).toBe(false);
    expect(spawnSyncMock.mock.calls.some(([, args]) => args[0] === "-B")).toBe(
      false,
    );
  },
);

test("stops when npm is terminated by a signal", () => {
  spawnSyncMock.mockReturnValueOnce({
    ...createCommandResult("", null),
    signal: "SIGTERM",
  });
  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).toThrow(
    /SIGTERM/,
  );
  expect(spawnSyncMock).toHaveBeenCalledTimes(1);
});

test.each([
  { ...createCommandResult("", null), error: new Error("ENOENT") },
  createCommandResult("", 1),
])("reports unavailable AWS CLI as a warning", (result) => {
  const successfulCommand = spawnSyncMock.getMockImplementation();
  spawnSyncMock.mockImplementation((executable, args, options) =>
    executable === "aws"
      ? result
      : successfulCommand(executable, args, options),
  );

  expect(() => setUpDevelopmentEnvironment({ repositoryRoot })).not.toThrow();
  expect(console.warn).toHaveBeenCalledWith(expect.stringMatching(/AWS CLI/));
});
