"""Deterministic Markdown projection of the canonical editing policy.

Every rule and human clause is rendered from the policy graph. Core constraint
parameters become requirement facts; SPARQL constraints and human clauses use
their co-located curated prose. Nothing is generated by a language model.
"""
from __future__ import annotations

from rdflib import RDF, RDFS, SH, Graph, Literal, URIRef
from rdflib.collection import Collection
from rdflib.namespace import DCTERMS

from .namespaces import REPOSITORY_ROOT, UOP
from .policy import Policy

GENERATED_DOCUMENT_PATH = REPOSITORY_ROOT / "docs" / "policy" / "Editing-Policy.generated.md"

_PREFIXES = {
    "http://purl.org/dc/terms/": "dcterms",
    "http://www.w3.org/2000/01/rdf-schema#": "rdfs",
    "http://www.w3.org/2004/02/skos/core#": "skos",
    "http://www.w3.org/2002/07/owl#": "owl",
    "http://www.w3.org/2001/XMLSchema#": "xsd",
    "http://www.w3.org/1999/02/22-rdf-syntax-ns#": "rdf",
    "http://www.w3.org/ns/dcat#": "dcat",
    "http://schema.org/": "schema",
    "http://www.w3.org/ns/shacl#": "sh",
    "https://haddenindustries.com/ontology/universal/core/": "uc",
}


def markdown_inline(text: str) -> str:
    """Escape characters that would change meaning inside GitHub Markdown inline text."""
    return (
        text.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("`", "\\`")
        .replace("<", "\\<")
        .replace(">", "\\>")
        .replace("*", "\\*")
        .replace("_", "\\_")
    )


def markdown_paragraphs(text: str) -> str:
    """Curated prose is trusted Markdown authored in the policy; normalise line endings only."""
    return "\n".join(line.rstrip() for line in text.replace("\r\n", "\n").strip().split("\n"))


def code(text: str) -> str:
    fence = "`" * (max((len(run) for run in text.split("`") if run == ""), default=0) + 1)
    return f"{fence}{text}{fence}"


def curie(term) -> str:
    text = str(term)
    for namespace, prefix in _PREFIXES.items():
        if text.startswith(namespace):
            return f"{prefix}:{text[len(namespace):]}"
    return text


def _english(graph: Graph, subject, predicate) -> str:
    for value in graph.objects(subject, predicate):
        if isinstance(value, Literal) and (value.language or "").lower().startswith("en"):
            return str(value)
    for value in graph.objects(subject, predicate):
        return str(value)
    return ""


def _order(graph: Graph, subject) -> int:
    value = graph.value(subject, SH.order)
    return int(value) if value is not None else 1_000_000


def _path_text(graph: Graph, path_node) -> str:
    if isinstance(path_node, URIRef):
        return code(curie(path_node))
    inverse = graph.value(path_node, SH.inversePath)
    if inverse is not None:
        return "inverse of " + _path_text(graph, inverse)
    return code("(path)")


def constraint_facts(graph: Graph, shape) -> list[str]:
    """Render the supported Core parameters of one constraint shape as reader facts."""
    facts = []
    path = graph.value(shape, SH.path)
    subject = _path_text(graph, path) if path is not None else "the entity"
    minimum = graph.value(shape, SH.minCount)
    maximum = graph.value(shape, SH.maxCount)
    if minimum is not None and maximum is not None and int(minimum) == int(maximum):
        facts.append(f"{subject}: exactly {'one value' if int(minimum) == 1 else f'{int(minimum)} values'}")
    else:
        if minimum is not None:
            facts.append(f"{subject}: at least {'one value' if int(minimum) == 1 else f'{int(minimum)} values'}")
        if maximum is not None:
            facts.append(f"{subject}: at most {'one value' if int(maximum) == 1 else f'{int(maximum)} values'}")
    datatype = graph.value(shape, SH.datatype)
    if datatype is not None:
        facts.append(f"{subject}: datatype {code(curie(datatype))}")
    node_kind = graph.value(shape, SH.nodeKind)
    if node_kind is not None:
        facts.append(f"{subject}: node kind {code(curie(node_kind))}")
    class_ = graph.value(shape, SH["class"])
    if class_ is not None:
        facts.append(f"{subject}: values are instances of {code(curie(class_))}")
    pattern = graph.value(shape, SH.pattern)
    if pattern is not None:
        flags = graph.value(shape, SH.flags)
        facts.append(f"{subject}: matches the pattern {code(str(pattern))}" + (f" (flags {code(str(flags))})" if flags else ""))
    languages = graph.value(shape, SH.languageIn)
    if languages is not None:
        facts.append(f"{subject}: language tag in {', '.join(code(str(item)) for item in Collection(graph, languages))}")
    if graph.value(shape, SH.uniqueLang) is not None and bool(graph.value(shape, SH.uniqueLang)):
        facts.append(f"{subject}: at most one value per language")
    allowed = graph.value(shape, SH["in"])
    if allowed is not None:
        facts.append(f"{subject}: one of {', '.join(code(curie(item)) for item in Collection(graph, allowed))}")
    for parameter, label in ((SH.minLength, "minimum length"), (SH.maxLength, "maximum length")):
        value = graph.value(shape, parameter)
        if value is not None:
            facts.append(f"{subject}: {label} {int(value)}")
    if graph.value(shape, SH.hasValue) is not None:
        facts.append(f"{subject}: includes the value {code(curie(graph.value(shape, SH.hasValue)))}")
    for sparql in graph.objects(shape, SH.sparql):
        message = _english(graph, sparql, SH.message) or "SPARQL-based check"
        facts.append(f"{subject}: {markdown_inline(message)} (SPARQL-based check; see the policy source)")
    severity = graph.value(shape, SH.severity)
    if severity == SH.Warning:
        facts = [f"{fact} — recommendation (SHOULD), reported as a warning" for fact in facts]
    return facts


def render_requirement(graph: Graph, requirement, requirement_id: str) -> list[str]:
    lines = []
    strength = str(graph.value(requirement, UOP.normativeStrength))
    name = markdown_inline(_english(graph, requirement, SH.name))
    human = (requirement, RDF.type, UOP.HumanClause) in graph
    lines.append(f"### {requirement_id} — {name} ({strength}{', human review' if human else ''})")
    lines.append("")
    lines.append(markdown_paragraphs(_english(graph, requirement, SH.description)))
    lines.append("")
    if human:
        lines.append("**Review obligation:** this clause is discharged by human review and recorded in the pull request; no executable check establishes it.")
        lines.append("")
    else:
        target = graph.value(requirement, SH.target)
        applies = _english(graph, target, RDFS.comment) if target is not None else ""
        for target_class in graph.objects(requirement, SH.targetClass):
            applies = f"instances of {code(curie(target_class))}"
        for subjects_of in graph.objects(requirement, SH.targetSubjectsOf):
            applies = f"subjects of {code(curie(subjects_of))}"
        if applies:
            lines.append(f"**Applies to:** {applies}")
            lines.append("")
        facts = []
        for shape in sorted(graph.objects(requirement, SH.property), key=str):
            facts.extend(constraint_facts(graph, shape))
        facts.extend(constraint_facts(graph, requirement))
        if facts:
            lines.append("**Executable constraints:**")
            lines.append("")
            lines.extend(f"- {fact}" for fact in facts)
            lines.append("")
    sources = sorted(str(value) for value in graph.objects(requirement, DCTERMS.source))
    lines.append("**Source:** " + "; ".join(markdown_inline(source) for source in sources))
    lines.append("")
    return lines


def render_editing_policy(policy: Policy) -> str:
    graph = policy.rules
    root = next(iter(graph.subjects(RDF.type, UOP.Policy)))
    lines = [f"# {markdown_inline(_english(graph, root, DCTERMS.title))}", ""]
    lines.append(markdown_paragraphs(_english(graph, root, DCTERMS.description)))
    lines.append("")
    lines.append(
        f"Generated from the canonical policy graph (policy identity `{policy.identity}`). "
        "Do not edit this page by hand; change the policy sources under `policy/` and regenerate."
    )
    lines.append("")
    ids = policy.requirement_ids()
    groups = sorted(graph.subjects(RDF.type, SH.PropertyGroup), key=lambda group: (_order(graph, group), str(group)))
    for group in groups:
        members = sorted(
            (requirement for requirement in ids if graph.value(requirement, SH.group) == group),
            key=lambda requirement: (_order(graph, requirement), ids[requirement]),
        )
        if not members:
            continue
        lines.append(f"## {markdown_inline(_english(graph, group, RDFS.label))}")
        lines.append("")
        comment = _english(graph, group, RDFS.comment)
        if comment:
            lines.append(markdown_paragraphs(comment))
            lines.append("")
        for requirement in members:
            lines.extend(render_requirement(graph, requirement, ids[requirement]))
    text = "\n".join(lines).rstrip("\n") + "\n"
    return text
