/** Generate the dependency-free validator, or check it without writing files. */
import { readFileSync, writeFileSync } from "node:fs";
import Ajv from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { format } from "prettier";
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
const target = new URL("./pullRequestCheckPlanValidator.js", import.meta.url);
const schema = JSON.parse(
  readFileSync(
    new URL("./pullRequestCheckPlan.schema.json", import.meta.url),
    "utf8",
  ),
);
const ajv = new Ajv({
  strict: true,
  code: { source: true, esm: true },
  allErrors: true,
});
const bundle = await build({
  stdin: {
    contents: standaloneCode(ajv, ajv.compile(schema)),
    resolveDir: fileURLToPath(new URL("../", import.meta.url)),
    sourcefile: "standalone-validator.js",
  },
  bundle: true,
  write: false,
  format: "esm",
  platform: "node",
  legalComments: "none",
});
const generated = await format(
  "// Generated by generatePullRequestCheckPlanValidator.js; do not edit.\n/* eslint-disable no-unused-vars, no-redeclare, no-useless-assignment -- Ajv emits shared signature fields and reusable validation temporaries. Schema and freshness tests govern this generated code. */\n" +
    bundle.outputFiles[0].text,
  { parser: "babel" },
);
if (
  process.argv.length !== 3 ||
  !["--write", "--check"].includes(process.argv[2])
)
  throw new Error("Use --write or --check.");
if (process.argv[2] === "--write") writeFileSync(target, generated);
else if (readFileSync(target, "utf8") !== generated)
  throw new Error("Plan validator is stale; regenerate with --write.");
