// Generated by generatePullRequestCheckPlanValidator.js; do not edit.
/* eslint-disable no-unused-vars, no-redeclare, no-useless-assignment -- Ajv emits shared signature fields and reusable validation temporaries. Schema and freshness tests govern this generated code. */
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) =>
  function __require() {
    try {
      return (
        mod ||
          (0, cb[__getOwnPropNames(cb)[0]])(
            (mod = { exports: {} }).exports,
            mod,
          ),
        mod.exports
      );
    } catch (e) {
      throw ((mod = 0), e);
    }
  };

// node_modules/fast-deep-equal/index.js
var require_fast_deep_equal = __commonJS({
  "node_modules/fast-deep-equal/index.js"(exports, module) {
    "use strict";
    module.exports = function equal(a, b) {
      if (a === b) return true;
      if (a && b && typeof a == "object" && typeof b == "object") {
        if (a.constructor !== b.constructor) return false;
        var length, i, keys;
        if (Array.isArray(a)) {
          length = a.length;
          if (length != b.length) return false;
          for (i = length; i-- !== 0;) if (!equal(a[i], b[i])) return false;
          return true;
        }
        if (a.constructor === RegExp)
          return a.source === b.source && a.flags === b.flags;
        if (a.valueOf !== Object.prototype.valueOf)
          return a.valueOf() === b.valueOf();
        if (a.toString !== Object.prototype.toString)
          return a.toString() === b.toString();
        keys = Object.keys(a);
        length = keys.length;
        if (length !== Object.keys(b).length) return false;
        for (i = length; i-- !== 0;)
          if (!Object.prototype.hasOwnProperty.call(b, keys[i])) return false;
        for (i = length; i-- !== 0;) {
          var key = keys[i];
          if (!equal(a[key], b[key])) return false;
        }
        return true;
      }
      return a !== a && b !== b;
    };
  },
});

// node_modules/ajv/dist/runtime/equal.js
var require_equal = __commonJS({
  "node_modules/ajv/dist/runtime/equal.js"(exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var equal = require_fast_deep_equal();
    equal.code = 'require("ajv/dist/runtime/equal").default';
    exports.default = equal;
  },
});

// standalone-validator.js
var validate = validate20;
var standalone_validator_default = validate20;
var schema31 = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "packageMode",
    "mode",
    "revision",
    "comparisonBase",
    "scopes",
    "requiredJobs",
  ],
  properties: {
    schemaVersion: { const: 4 },
    packageMode: { enum: ["disabled", "ci", "manual"] },
    mode: { enum: ["changed", "full"] },
    revision: { type: "string", pattern: "^[a-f0-9]{40}$" },
    comparisonBase: {
      anyOf: [{ type: "null" }, { type: "string", pattern: "^[a-f0-9]{40}$" }],
    },
    scopes: {
      type: "object",
      additionalProperties: false,
      required: [
        "style_tooling",
        "python_style",
        "python_tests",
        "python_setup_tests",
        "documentation",
        "ontology_validation",
        "ontology_validation_workflow",
        "ontology_entity_contracts",
        "ontology_policy_qa",
        "ontology_qualification",
        "agent_skills_lock",
        "development",
        "product_tests",
        "ci_control",
        "mcp_artifacts",
        "website_build",
        "mcp_docs",
        "mcp_application",
        "mcp_release_qualification",
      ],
      properties: {
        style_tooling: { type: "boolean" },
        python_style: { type: "boolean" },
        python_tests: { type: "boolean" },
        python_setup_tests: { type: "boolean" },
        documentation: { type: "boolean" },
        ontology_validation: { type: "boolean" },
        ontology_validation_workflow: { type: "boolean" },
        ontology_entity_contracts: { type: "boolean" },
        ontology_policy_qa: { type: "boolean" },
        ontology_qualification: { type: "boolean" },
        agent_skills_lock: { type: "boolean" },
        development: { type: "boolean" },
        product_tests: { type: "boolean" },
        ci_control: { type: "boolean" },
        mcp_artifacts: { type: "boolean" },
        website_build: { type: "boolean" },
        mcp_docs: { type: "boolean" },
        mcp_application: { type: "boolean" },
        mcp_release_qualification: { type: "boolean" },
      },
    },
    requiredJobs: {
      type: "array",
      uniqueItems: true,
      items: {
        enum: ["development", "ontology", "node", "website", "distribution"],
      },
    },
  },
  allOf: [
    {
      if: { properties: { mode: { const: "changed" } } },
      then: {
        properties: {
          comparisonBase: { type: "string", pattern: "^[a-f0-9]{40}$" },
        },
      },
      else: {
        properties: {
          comparisonBase: { type: "null" },
          scopes: {
            properties: {
              style_tooling: { const: true },
              python_style: { const: true },
              python_tests: { const: true },
              python_setup_tests: { const: true },
              documentation: { const: true },
              ontology_validation: { const: true },
              ontology_validation_workflow: { const: true },
              ontology_entity_contracts: { const: true },
              ontology_policy_qa: { const: true },
              ontology_qualification: { const: true },
              agent_skills_lock: { const: true },
              development: { const: true },
              product_tests: { const: true },
              ci_control: { const: true },
              website_build: { const: true },
              mcp_docs: { const: true },
              mcp_application: { const: true },
            },
            type: "object",
          },
        },
      },
    },
    {
      if: { properties: { packageMode: { const: "disabled" } } },
      then: {
        properties: {
          scopes: {
            properties: {
              mcp_artifacts: { const: false },
              mcp_release_qualification: { const: false },
            },
            type: "object",
          },
        },
      },
    },
    {
      if: { properties: { packageMode: { const: "manual" } } },
      then: {
        properties: {
          mode: { const: "full" },
          scopes: {
            properties: {
              mcp_artifacts: { const: true },
              mcp_release_qualification: { const: true },
            },
            type: "object",
          },
        },
      },
    },
    {
      if: { properties: { packageMode: { const: "ci" } } },
      then: {
        properties: {
          scopes: {
            properties: { mcp_release_qualification: { const: false } },
            type: "object",
          },
        },
      },
    },
    {
      if: {
        properties: { packageMode: { const: "ci" }, mode: { const: "full" } },
      },
      then: {
        properties: {
          scopes: {
            properties: { mcp_artifacts: { const: true } },
            type: "object",
          },
        },
      },
    },
    {
      if: {
        properties: {
          scopes: {
            properties: { mcp_artifacts: { const: true } },
            type: "object",
          },
        },
      },
      then: {
        properties: {
          scopes: {
            properties: { mcp_application: { const: true } },
            type: "object",
          },
        },
      },
    },
    {
      if: {
        properties: {
          scopes: {
            properties: { mcp_release_qualification: { const: true } },
            type: "object",
          },
        },
      },
      then: {
        properties: {
          scopes: {
            properties: { mcp_artifacts: { const: true } },
            type: "object",
          },
        },
      },
    },
  ],
};
var pattern4 = new RegExp("^[a-f0-9]{40}$", "u");
var func1 = Object.prototype.hasOwnProperty;
var func0 = require_equal().default;
function validate20(
  data,
  {
    instancePath = "",
    parentData,
    parentDataProperty,
    rootData = data,
    dynamicAnchors = {},
  } = {},
) {
  let vErrors = null;
  let errors = 0;
  const evaluated0 = validate20.evaluated;
  if (evaluated0.dynamicProps) {
    evaluated0.props = void 0;
  }
  if (evaluated0.dynamicItems) {
    evaluated0.items = void 0;
  }
  const _errs2 = errors;
  let valid1 = true;
  const _errs3 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.mode !== void 0) {
      if ("changed" !== data.mode) {
        const err0 = {};
        if (vErrors === null) {
          vErrors = [err0];
        } else {
          vErrors.push(err0);
        }
        errors++;
      }
    }
  }
  var _valid0 = _errs3 === errors;
  errors = _errs2;
  if (vErrors !== null) {
    if (_errs2) {
      vErrors.length = _errs2;
    } else {
      vErrors = null;
    }
  }
  let ifClause0;
  if (_valid0) {
    const _errs5 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.comparisonBase !== void 0) {
        let data1 = data.comparisonBase;
        if (typeof data1 === "string") {
          if (!pattern4.test(data1)) {
            const err1 = {
              instancePath: instancePath + "/comparisonBase",
              schemaPath: "#/allOf/0/then/properties/comparisonBase/pattern",
              keyword: "pattern",
              params: { pattern: "^[a-f0-9]{40}$" },
              message: 'must match pattern "^[a-f0-9]{40}$"',
            };
            if (vErrors === null) {
              vErrors = [err1];
            } else {
              vErrors.push(err1);
            }
            errors++;
          }
        } else {
          const err2 = {
            instancePath: instancePath + "/comparisonBase",
            schemaPath: "#/allOf/0/then/properties/comparisonBase/type",
            keyword: "type",
            params: { type: "string" },
            message: "must be string",
          };
          if (vErrors === null) {
            vErrors = [err2];
          } else {
            vErrors.push(err2);
          }
          errors++;
        }
      }
    }
    var _valid0 = _errs5 === errors;
    valid1 = _valid0;
    if (valid1) {
      var props0 = {};
      props0.comparisonBase = true;
      props0.mode = true;
    }
    ifClause0 = "then";
  } else {
    const _errs8 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.comparisonBase !== void 0) {
        if (data.comparisonBase !== null) {
          const err3 = {
            instancePath: instancePath + "/comparisonBase",
            schemaPath: "#/allOf/0/else/properties/comparisonBase/type",
            keyword: "type",
            params: { type: "null" },
            message: "must be null",
          };
          if (vErrors === null) {
            vErrors = [err3];
          } else {
            vErrors.push(err3);
          }
          errors++;
        }
      }
      if (data.scopes !== void 0) {
        let data3 = data.scopes;
        if (data3 && typeof data3 == "object" && !Array.isArray(data3)) {
          if (data3.style_tooling !== void 0) {
            if (true !== data3.style_tooling) {
              const err4 = {
                instancePath: instancePath + "/scopes/style_tooling",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/style_tooling/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err4];
              } else {
                vErrors.push(err4);
              }
              errors++;
            }
          }
          if (data3.python_style !== void 0) {
            if (true !== data3.python_style) {
              const err5 = {
                instancePath: instancePath + "/scopes/python_style",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/python_style/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err5];
              } else {
                vErrors.push(err5);
              }
              errors++;
            }
          }
          if (data3.python_tests !== void 0) {
            if (true !== data3.python_tests) {
              const err6 = {
                instancePath: instancePath + "/scopes/python_tests",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/python_tests/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err6];
              } else {
                vErrors.push(err6);
              }
              errors++;
            }
          }
          if (data3.python_setup_tests !== void 0) {
            if (true !== data3.python_setup_tests) {
              const err7 = {
                instancePath: instancePath + "/scopes/python_setup_tests",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/python_setup_tests/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err7];
              } else {
                vErrors.push(err7);
              }
              errors++;
            }
          }
          if (data3.documentation !== void 0) {
            if (true !== data3.documentation) {
              const err8 = {
                instancePath: instancePath + "/scopes/documentation",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/documentation/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err8];
              } else {
                vErrors.push(err8);
              }
              errors++;
            }
          }
          if (data3.ontology_validation !== void 0) {
            if (true !== data3.ontology_validation) {
              const err9 = {
                instancePath: instancePath + "/scopes/ontology_validation",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_validation/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err9];
              } else {
                vErrors.push(err9);
              }
              errors++;
            }
          }
          if (data3.ontology_validation_workflow !== void 0) {
            if (true !== data3.ontology_validation_workflow) {
              const err10 = {
                instancePath:
                  instancePath + "/scopes/ontology_validation_workflow",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_validation_workflow/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err10];
              } else {
                vErrors.push(err10);
              }
              errors++;
            }
          }
          if (data3.ontology_entity_contracts !== void 0) {
            if (true !== data3.ontology_entity_contracts) {
              const err11 = {
                instancePath:
                  instancePath + "/scopes/ontology_entity_contracts",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_entity_contracts/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err11];
              } else {
                vErrors.push(err11);
              }
              errors++;
            }
          }
          if (data3.ontology_policy_qa !== void 0) {
            if (true !== data3.ontology_policy_qa) {
              const err12 = {
                instancePath: instancePath + "/scopes/ontology_policy_qa",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_policy_qa/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err12];
              } else {
                vErrors.push(err12);
              }
              errors++;
            }
          }
          if (data3.ontology_qualification !== void 0) {
            if (true !== data3.ontology_qualification) {
              const err13 = {
                instancePath: instancePath + "/scopes/ontology_qualification",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_qualification/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err13];
              } else {
                vErrors.push(err13);
              }
              errors++;
            }
          }
          if (data3.agent_skills_lock !== void 0) {
            if (true !== data3.agent_skills_lock) {
              const err14 = {
                instancePath: instancePath + "/scopes/agent_skills_lock",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/agent_skills_lock/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err14];
              } else {
                vErrors.push(err14);
              }
              errors++;
            }
          }
          if (data3.development !== void 0) {
            if (true !== data3.development) {
              const err15 = {
                instancePath: instancePath + "/scopes/development",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/development/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err15];
              } else {
                vErrors.push(err15);
              }
              errors++;
            }
          }
          if (data3.product_tests !== void 0) {
            if (true !== data3.product_tests) {
              const err16 = {
                instancePath: instancePath + "/scopes/product_tests",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/product_tests/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err16];
              } else {
                vErrors.push(err16);
              }
              errors++;
            }
          }
          if (data3.ci_control !== void 0) {
            if (true !== data3.ci_control) {
              const err17 = {
                instancePath: instancePath + "/scopes/ci_control",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ci_control/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err17];
              } else {
                vErrors.push(err17);
              }
              errors++;
            }
          }
          if (data3.website_build !== void 0) {
            if (true !== data3.website_build) {
              const err18 = {
                instancePath: instancePath + "/scopes/website_build",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/website_build/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err18];
              } else {
                vErrors.push(err18);
              }
              errors++;
            }
          }
          if (data3.mcp_docs !== void 0) {
            if (true !== data3.mcp_docs) {
              const err19 = {
                instancePath: instancePath + "/scopes/mcp_docs",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/mcp_docs/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err19];
              } else {
                vErrors.push(err19);
              }
              errors++;
            }
          }
          if (data3.mcp_application !== void 0) {
            if (true !== data3.mcp_application) {
              const err20 = {
                instancePath: instancePath + "/scopes/mcp_application",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/mcp_application/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err20];
              } else {
                vErrors.push(err20);
              }
              errors++;
            }
          }
        } else {
          const err21 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/0/else/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err21];
          } else {
            vErrors.push(err21);
          }
          errors++;
        }
      }
    }
    var _valid0 = _errs8 === errors;
    valid1 = _valid0;
    if (valid1) {
      if (props0 !== true) {
        props0 = props0 || {};
        props0.comparisonBase = true;
        props0.scopes = true;
      }
    }
    ifClause0 = "else";
  }
  if (!valid1) {
    const err22 = {
      instancePath,
      schemaPath: "#/allOf/0/if",
      keyword: "if",
      params: { failingKeyword: ifClause0 },
      message: 'must match "' + ifClause0 + '" schema',
    };
    if (vErrors === null) {
      vErrors = [err22];
    } else {
      vErrors.push(err22);
    }
    errors++;
  }
  const _errs31 = errors;
  let valid6 = true;
  const _errs32 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.packageMode !== void 0) {
      if ("disabled" !== data.packageMode) {
        const err23 = {};
        if (vErrors === null) {
          vErrors = [err23];
        } else {
          vErrors.push(err23);
        }
        errors++;
      }
    }
  }
  var _valid1 = _errs32 === errors;
  errors = _errs31;
  if (vErrors !== null) {
    if (_errs31) {
      vErrors.length = _errs31;
    } else {
      vErrors = null;
    }
  }
  if (_valid1) {
    const _errs34 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.scopes !== void 0) {
        let data22 = data.scopes;
        if (data22 && typeof data22 == "object" && !Array.isArray(data22)) {
          if (data22.mcp_artifacts !== void 0) {
            if (false !== data22.mcp_artifacts) {
              const err24 = {
                instancePath: instancePath + "/scopes/mcp_artifacts",
                schemaPath:
                  "#/allOf/1/then/properties/scopes/properties/mcp_artifacts/const",
                keyword: "const",
                params: { allowedValue: false },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err24];
              } else {
                vErrors.push(err24);
              }
              errors++;
            }
          }
          if (data22.mcp_release_qualification !== void 0) {
            if (false !== data22.mcp_release_qualification) {
              const err25 = {
                instancePath:
                  instancePath + "/scopes/mcp_release_qualification",
                schemaPath:
                  "#/allOf/1/then/properties/scopes/properties/mcp_release_qualification/const",
                keyword: "const",
                params: { allowedValue: false },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err25];
              } else {
                vErrors.push(err25);
              }
              errors++;
            }
          }
        } else {
          const err26 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/1/then/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err26];
          } else {
            vErrors.push(err26);
          }
          errors++;
        }
      }
    }
    var _valid1 = _errs34 === errors;
    valid6 = _valid1;
    if (valid6) {
      var props1 = {};
      props1.scopes = true;
      props1.packageMode = true;
    }
  }
  if (!valid6) {
    const err27 = {
      instancePath,
      schemaPath: "#/allOf/1/if",
      keyword: "if",
      params: { failingKeyword: "then" },
      message: 'must match "then" schema',
    };
    if (vErrors === null) {
      vErrors = [err27];
    } else {
      vErrors.push(err27);
    }
    errors++;
  }
  if (props0 !== true && props1 !== void 0) {
    if (props1 === true) {
      props0 = true;
    } else {
      props0 = props0 || {};
      Object.assign(props0, props1);
    }
  }
  const _errs40 = errors;
  let valid10 = true;
  const _errs41 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.packageMode !== void 0) {
      if ("manual" !== data.packageMode) {
        const err28 = {};
        if (vErrors === null) {
          vErrors = [err28];
        } else {
          vErrors.push(err28);
        }
        errors++;
      }
    }
  }
  var _valid2 = _errs41 === errors;
  errors = _errs40;
  if (vErrors !== null) {
    if (_errs40) {
      vErrors.length = _errs40;
    } else {
      vErrors = null;
    }
  }
  if (_valid2) {
    const _errs43 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.mode !== void 0) {
        if ("full" !== data.mode) {
          const err29 = {
            instancePath: instancePath + "/mode",
            schemaPath: "#/allOf/2/then/properties/mode/const",
            keyword: "const",
            params: { allowedValue: "full" },
            message: "must be equal to constant",
          };
          if (vErrors === null) {
            vErrors = [err29];
          } else {
            vErrors.push(err29);
          }
          errors++;
        }
      }
      if (data.scopes !== void 0) {
        let data27 = data.scopes;
        if (data27 && typeof data27 == "object" && !Array.isArray(data27)) {
          if (data27.mcp_artifacts !== void 0) {
            if (true !== data27.mcp_artifacts) {
              const err30 = {
                instancePath: instancePath + "/scopes/mcp_artifacts",
                schemaPath:
                  "#/allOf/2/then/properties/scopes/properties/mcp_artifacts/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err30];
              } else {
                vErrors.push(err30);
              }
              errors++;
            }
          }
          if (data27.mcp_release_qualification !== void 0) {
            if (true !== data27.mcp_release_qualification) {
              const err31 = {
                instancePath:
                  instancePath + "/scopes/mcp_release_qualification",
                schemaPath:
                  "#/allOf/2/then/properties/scopes/properties/mcp_release_qualification/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err31];
              } else {
                vErrors.push(err31);
              }
              errors++;
            }
          }
        } else {
          const err32 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/2/then/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err32];
          } else {
            vErrors.push(err32);
          }
          errors++;
        }
      }
    }
    var _valid2 = _errs43 === errors;
    valid10 = _valid2;
    if (valid10) {
      var props2 = {};
      props2.mode = true;
      props2.scopes = true;
      props2.packageMode = true;
    }
  }
  if (!valid10) {
    const err33 = {
      instancePath,
      schemaPath: "#/allOf/2/if",
      keyword: "if",
      params: { failingKeyword: "then" },
      message: 'must match "then" schema',
    };
    if (vErrors === null) {
      vErrors = [err33];
    } else {
      vErrors.push(err33);
    }
    errors++;
  }
  if (props0 !== true && props2 !== void 0) {
    if (props2 === true) {
      props0 = true;
    } else {
      props0 = props0 || {};
      Object.assign(props0, props2);
    }
  }
  const _errs50 = errors;
  let valid14 = true;
  const _errs51 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.packageMode !== void 0) {
      if ("ci" !== data.packageMode) {
        const err34 = {};
        if (vErrors === null) {
          vErrors = [err34];
        } else {
          vErrors.push(err34);
        }
        errors++;
      }
    }
  }
  var _valid3 = _errs51 === errors;
  errors = _errs50;
  if (vErrors !== null) {
    if (_errs50) {
      vErrors.length = _errs50;
    } else {
      vErrors = null;
    }
  }
  if (_valid3) {
    const _errs53 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.scopes !== void 0) {
        let data31 = data.scopes;
        if (data31 && typeof data31 == "object" && !Array.isArray(data31)) {
          if (data31.mcp_release_qualification !== void 0) {
            if (false !== data31.mcp_release_qualification) {
              const err35 = {
                instancePath:
                  instancePath + "/scopes/mcp_release_qualification",
                schemaPath:
                  "#/allOf/3/then/properties/scopes/properties/mcp_release_qualification/const",
                keyword: "const",
                params: { allowedValue: false },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err35];
              } else {
                vErrors.push(err35);
              }
              errors++;
            }
          }
        } else {
          const err36 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/3/then/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err36];
          } else {
            vErrors.push(err36);
          }
          errors++;
        }
      }
    }
    var _valid3 = _errs53 === errors;
    valid14 = _valid3;
    if (valid14) {
      var props3 = {};
      props3.scopes = true;
      props3.packageMode = true;
    }
  }
  if (!valid14) {
    const err37 = {
      instancePath,
      schemaPath: "#/allOf/3/if",
      keyword: "if",
      params: { failingKeyword: "then" },
      message: 'must match "then" schema',
    };
    if (vErrors === null) {
      vErrors = [err37];
    } else {
      vErrors.push(err37);
    }
    errors++;
  }
  if (props0 !== true && props3 !== void 0) {
    if (props3 === true) {
      props0 = true;
    } else {
      props0 = props0 || {};
      Object.assign(props0, props3);
    }
  }
  const _errs58 = errors;
  let valid18 = true;
  const _errs59 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.packageMode !== void 0) {
      const _errs60 = errors;
      if ("ci" !== data.packageMode) {
        const err38 = {};
        if (vErrors === null) {
          vErrors = [err38];
        } else {
          vErrors.push(err38);
        }
        errors++;
      }
      var valid19 = _errs60 === errors;
    } else {
      var valid19 = true;
    }
    if (valid19) {
      if (data.mode !== void 0) {
        const _errs61 = errors;
        if ("full" !== data.mode) {
          const err39 = {};
          if (vErrors === null) {
            vErrors = [err39];
          } else {
            vErrors.push(err39);
          }
          errors++;
        }
        var valid19 = _errs61 === errors;
      } else {
        var valid19 = true;
      }
    }
  }
  var _valid4 = _errs59 === errors;
  errors = _errs58;
  if (vErrors !== null) {
    if (_errs58) {
      vErrors.length = _errs58;
    } else {
      vErrors = null;
    }
  }
  if (_valid4) {
    const _errs62 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.scopes !== void 0) {
        let data35 = data.scopes;
        if (data35 && typeof data35 == "object" && !Array.isArray(data35)) {
          if (data35.mcp_artifacts !== void 0) {
            if (true !== data35.mcp_artifacts) {
              const err40 = {
                instancePath: instancePath + "/scopes/mcp_artifacts",
                schemaPath:
                  "#/allOf/4/then/properties/scopes/properties/mcp_artifacts/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err40];
              } else {
                vErrors.push(err40);
              }
              errors++;
            }
          }
        } else {
          const err41 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/4/then/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err41];
          } else {
            vErrors.push(err41);
          }
          errors++;
        }
      }
    }
    var _valid4 = _errs62 === errors;
    valid18 = _valid4;
    if (valid18) {
      var props4 = {};
      props4.scopes = true;
      props4.packageMode = true;
      props4.mode = true;
    }
  }
  if (!valid18) {
    const err42 = {
      instancePath,
      schemaPath: "#/allOf/4/if",
      keyword: "if",
      params: { failingKeyword: "then" },
      message: 'must match "then" schema',
    };
    if (vErrors === null) {
      vErrors = [err42];
    } else {
      vErrors.push(err42);
    }
    errors++;
  }
  if (props0 !== true && props4 !== void 0) {
    if (props4 === true) {
      props0 = true;
    } else {
      props0 = props0 || {};
      Object.assign(props0, props4);
    }
  }
  const _errs67 = errors;
  let valid22 = true;
  const _errs68 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.scopes !== void 0) {
      let data37 = data.scopes;
      const _errs69 = errors;
      if (errors === _errs69) {
        if (data37 && typeof data37 == "object" && !Array.isArray(data37)) {
          if (data37.mcp_artifacts !== void 0) {
            if (true !== data37.mcp_artifacts) {
              const err43 = {};
              if (vErrors === null) {
                vErrors = [err43];
              } else {
                vErrors.push(err43);
              }
              errors++;
            }
          }
        } else {
          const err44 = {};
          if (vErrors === null) {
            vErrors = [err44];
          } else {
            vErrors.push(err44);
          }
          errors++;
        }
      }
    }
  }
  var _valid5 = _errs68 === errors;
  errors = _errs67;
  if (vErrors !== null) {
    if (_errs67) {
      vErrors.length = _errs67;
    } else {
      vErrors = null;
    }
  }
  if (_valid5) {
    const _errs72 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.scopes !== void 0) {
        let data39 = data.scopes;
        if (data39 && typeof data39 == "object" && !Array.isArray(data39)) {
          if (data39.mcp_application !== void 0) {
            if (true !== data39.mcp_application) {
              const err45 = {
                instancePath: instancePath + "/scopes/mcp_application",
                schemaPath:
                  "#/allOf/5/then/properties/scopes/properties/mcp_application/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err45];
              } else {
                vErrors.push(err45);
              }
              errors++;
            }
          }
        } else {
          const err46 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/5/then/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err46];
          } else {
            vErrors.push(err46);
          }
          errors++;
        }
      }
    }
    var _valid5 = _errs72 === errors;
    valid22 = _valid5;
    if (valid22) {
      var props5 = {};
      props5.scopes = true;
    }
  }
  if (!valid22) {
    const err47 = {
      instancePath,
      schemaPath: "#/allOf/5/if",
      keyword: "if",
      params: { failingKeyword: "then" },
      message: 'must match "then" schema',
    };
    if (vErrors === null) {
      vErrors = [err47];
    } else {
      vErrors.push(err47);
    }
    errors++;
  }
  if (props0 !== true && props5 !== void 0) {
    if (props5 === true) {
      props0 = true;
    } else {
      props0 = props0 || {};
      Object.assign(props0, props5);
    }
  }
  const _errs77 = errors;
  let valid27 = true;
  const _errs78 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.scopes !== void 0) {
      let data41 = data.scopes;
      const _errs79 = errors;
      if (errors === _errs79) {
        if (data41 && typeof data41 == "object" && !Array.isArray(data41)) {
          if (data41.mcp_release_qualification !== void 0) {
            if (true !== data41.mcp_release_qualification) {
              const err48 = {};
              if (vErrors === null) {
                vErrors = [err48];
              } else {
                vErrors.push(err48);
              }
              errors++;
            }
          }
        } else {
          const err49 = {};
          if (vErrors === null) {
            vErrors = [err49];
          } else {
            vErrors.push(err49);
          }
          errors++;
        }
      }
    }
  }
  var _valid6 = _errs78 === errors;
  errors = _errs77;
  if (vErrors !== null) {
    if (_errs77) {
      vErrors.length = _errs77;
    } else {
      vErrors = null;
    }
  }
  if (_valid6) {
    const _errs82 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.scopes !== void 0) {
        let data43 = data.scopes;
        if (data43 && typeof data43 == "object" && !Array.isArray(data43)) {
          if (data43.mcp_artifacts !== void 0) {
            if (true !== data43.mcp_artifacts) {
              const err50 = {
                instancePath: instancePath + "/scopes/mcp_artifacts",
                schemaPath:
                  "#/allOf/6/then/properties/scopes/properties/mcp_artifacts/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err50];
              } else {
                vErrors.push(err50);
              }
              errors++;
            }
          }
        } else {
          const err51 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/6/then/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err51];
          } else {
            vErrors.push(err51);
          }
          errors++;
        }
      }
    }
    var _valid6 = _errs82 === errors;
    valid27 = _valid6;
    if (valid27) {
      var props6 = {};
      props6.scopes = true;
    }
  }
  if (!valid27) {
    const err52 = {
      instancePath,
      schemaPath: "#/allOf/6/if",
      keyword: "if",
      params: { failingKeyword: "then" },
      message: 'must match "then" schema',
    };
    if (vErrors === null) {
      vErrors = [err52];
    } else {
      vErrors.push(err52);
    }
    errors++;
  }
  if (props0 !== true && props6 !== void 0) {
    if (props6 === true) {
      props0 = true;
    } else {
      props0 = props0 || {};
      Object.assign(props0, props6);
    }
  }
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.schemaVersion === void 0) {
      const err53 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "schemaVersion" },
        message: "must have required property 'schemaVersion'",
      };
      if (vErrors === null) {
        vErrors = [err53];
      } else {
        vErrors.push(err53);
      }
      errors++;
    }
    if (data.packageMode === void 0) {
      const err54 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "packageMode" },
        message: "must have required property 'packageMode'",
      };
      if (vErrors === null) {
        vErrors = [err54];
      } else {
        vErrors.push(err54);
      }
      errors++;
    }
    if (data.mode === void 0) {
      const err55 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "mode" },
        message: "must have required property 'mode'",
      };
      if (vErrors === null) {
        vErrors = [err55];
      } else {
        vErrors.push(err55);
      }
      errors++;
    }
    if (data.revision === void 0) {
      const err56 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "revision" },
        message: "must have required property 'revision'",
      };
      if (vErrors === null) {
        vErrors = [err56];
      } else {
        vErrors.push(err56);
      }
      errors++;
    }
    if (data.comparisonBase === void 0) {
      const err57 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "comparisonBase" },
        message: "must have required property 'comparisonBase'",
      };
      if (vErrors === null) {
        vErrors = [err57];
      } else {
        vErrors.push(err57);
      }
      errors++;
    }
    if (data.scopes === void 0) {
      const err58 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "scopes" },
        message: "must have required property 'scopes'",
      };
      if (vErrors === null) {
        vErrors = [err58];
      } else {
        vErrors.push(err58);
      }
      errors++;
    }
    if (data.requiredJobs === void 0) {
      const err59 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "requiredJobs" },
        message: "must have required property 'requiredJobs'",
      };
      if (vErrors === null) {
        vErrors = [err59];
      } else {
        vErrors.push(err59);
      }
      errors++;
    }
    for (const key0 in data) {
      if (!(
        key0 === "schemaVersion" ||
        key0 === "packageMode" ||
        key0 === "mode" ||
        key0 === "revision" ||
        key0 === "comparisonBase" ||
        key0 === "scopes" ||
        key0 === "requiredJobs"
      )) {
        const err60 = {
          instancePath,
          schemaPath: "#/additionalProperties",
          keyword: "additionalProperties",
          params: { additionalProperty: key0 },
          message: "must NOT have additional properties",
        };
        if (vErrors === null) {
          vErrors = [err60];
        } else {
          vErrors.push(err60);
        }
        errors++;
      }
    }
    if (data.schemaVersion !== void 0) {
      if (4 !== data.schemaVersion) {
        const err61 = {
          instancePath: instancePath + "/schemaVersion",
          schemaPath: "#/properties/schemaVersion/const",
          keyword: "const",
          params: { allowedValue: 4 },
          message: "must be equal to constant",
        };
        if (vErrors === null) {
          vErrors = [err61];
        } else {
          vErrors.push(err61);
        }
        errors++;
      }
    }
    if (data.packageMode !== void 0) {
      let data46 = data.packageMode;
      if (!(data46 === "disabled" || data46 === "ci" || data46 === "manual")) {
        const err62 = {
          instancePath: instancePath + "/packageMode",
          schemaPath: "#/properties/packageMode/enum",
          keyword: "enum",
          params: { allowedValues: schema31.properties.packageMode.enum },
          message: "must be equal to one of the allowed values",
        };
        if (vErrors === null) {
          vErrors = [err62];
        } else {
          vErrors.push(err62);
        }
        errors++;
      }
    }
    if (data.mode !== void 0) {
      let data47 = data.mode;
      if (!(data47 === "changed" || data47 === "full")) {
        const err63 = {
          instancePath: instancePath + "/mode",
          schemaPath: "#/properties/mode/enum",
          keyword: "enum",
          params: { allowedValues: schema31.properties.mode.enum },
          message: "must be equal to one of the allowed values",
        };
        if (vErrors === null) {
          vErrors = [err63];
        } else {
          vErrors.push(err63);
        }
        errors++;
      }
    }
    if (data.revision !== void 0) {
      let data48 = data.revision;
      if (typeof data48 === "string") {
        if (!pattern4.test(data48)) {
          const err64 = {
            instancePath: instancePath + "/revision",
            schemaPath: "#/properties/revision/pattern",
            keyword: "pattern",
            params: { pattern: "^[a-f0-9]{40}$" },
            message: 'must match pattern "^[a-f0-9]{40}$"',
          };
          if (vErrors === null) {
            vErrors = [err64];
          } else {
            vErrors.push(err64);
          }
          errors++;
        }
      } else {
        const err65 = {
          instancePath: instancePath + "/revision",
          schemaPath: "#/properties/revision/type",
          keyword: "type",
          params: { type: "string" },
          message: "must be string",
        };
        if (vErrors === null) {
          vErrors = [err65];
        } else {
          vErrors.push(err65);
        }
        errors++;
      }
    }
    if (data.comparisonBase !== void 0) {
      let data49 = data.comparisonBase;
      const _errs93 = errors;
      let valid33 = false;
      const _errs94 = errors;
      if (data49 !== null) {
        const err66 = {
          instancePath: instancePath + "/comparisonBase",
          schemaPath: "#/properties/comparisonBase/anyOf/0/type",
          keyword: "type",
          params: { type: "null" },
          message: "must be null",
        };
        if (vErrors === null) {
          vErrors = [err66];
        } else {
          vErrors.push(err66);
        }
        errors++;
      }
      var _valid7 = _errs94 === errors;
      valid33 = valid33 || _valid7;
      const _errs96 = errors;
      if (typeof data49 === "string") {
        if (!pattern4.test(data49)) {
          const err67 = {
            instancePath: instancePath + "/comparisonBase",
            schemaPath: "#/properties/comparisonBase/anyOf/1/pattern",
            keyword: "pattern",
            params: { pattern: "^[a-f0-9]{40}$" },
            message: 'must match pattern "^[a-f0-9]{40}$"',
          };
          if (vErrors === null) {
            vErrors = [err67];
          } else {
            vErrors.push(err67);
          }
          errors++;
        }
      } else {
        const err68 = {
          instancePath: instancePath + "/comparisonBase",
          schemaPath: "#/properties/comparisonBase/anyOf/1/type",
          keyword: "type",
          params: { type: "string" },
          message: "must be string",
        };
        if (vErrors === null) {
          vErrors = [err68];
        } else {
          vErrors.push(err68);
        }
        errors++;
      }
      var _valid7 = _errs96 === errors;
      valid33 = valid33 || _valid7;
      if (!valid33) {
        const err69 = {
          instancePath: instancePath + "/comparisonBase",
          schemaPath: "#/properties/comparisonBase/anyOf",
          keyword: "anyOf",
          params: {},
          message: "must match a schema in anyOf",
        };
        if (vErrors === null) {
          vErrors = [err69];
        } else {
          vErrors.push(err69);
        }
        errors++;
      } else {
        errors = _errs93;
        if (vErrors !== null) {
          if (_errs93) {
            vErrors.length = _errs93;
          } else {
            vErrors = null;
          }
        }
      }
    }
    if (data.scopes !== void 0) {
      let data50 = data.scopes;
      if (data50 && typeof data50 == "object" && !Array.isArray(data50)) {
        if (data50.style_tooling === void 0) {
          const err70 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "style_tooling" },
            message: "must have required property 'style_tooling'",
          };
          if (vErrors === null) {
            vErrors = [err70];
          } else {
            vErrors.push(err70);
          }
          errors++;
        }
        if (data50.python_style === void 0) {
          const err71 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "python_style" },
            message: "must have required property 'python_style'",
          };
          if (vErrors === null) {
            vErrors = [err71];
          } else {
            vErrors.push(err71);
          }
          errors++;
        }
        if (data50.python_tests === void 0) {
          const err72 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "python_tests" },
            message: "must have required property 'python_tests'",
          };
          if (vErrors === null) {
            vErrors = [err72];
          } else {
            vErrors.push(err72);
          }
          errors++;
        }
        if (data50.python_setup_tests === void 0) {
          const err73 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "python_setup_tests" },
            message: "must have required property 'python_setup_tests'",
          };
          if (vErrors === null) {
            vErrors = [err73];
          } else {
            vErrors.push(err73);
          }
          errors++;
        }
        if (data50.documentation === void 0) {
          const err74 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "documentation" },
            message: "must have required property 'documentation'",
          };
          if (vErrors === null) {
            vErrors = [err74];
          } else {
            vErrors.push(err74);
          }
          errors++;
        }
        if (data50.ontology_validation === void 0) {
          const err75 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_validation" },
            message: "must have required property 'ontology_validation'",
          };
          if (vErrors === null) {
            vErrors = [err75];
          } else {
            vErrors.push(err75);
          }
          errors++;
        }
        if (data50.ontology_validation_workflow === void 0) {
          const err76 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_validation_workflow" },
            message:
              "must have required property 'ontology_validation_workflow'",
          };
          if (vErrors === null) {
            vErrors = [err76];
          } else {
            vErrors.push(err76);
          }
          errors++;
        }
        if (data50.ontology_entity_contracts === void 0) {
          const err77 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_entity_contracts" },
            message: "must have required property 'ontology_entity_contracts'",
          };
          if (vErrors === null) {
            vErrors = [err77];
          } else {
            vErrors.push(err77);
          }
          errors++;
        }
        if (data50.ontology_policy_qa === void 0) {
          const err78 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_policy_qa" },
            message: "must have required property 'ontology_policy_qa'",
          };
          if (vErrors === null) {
            vErrors = [err78];
          } else {
            vErrors.push(err78);
          }
          errors++;
        }
        if (data50.ontology_qualification === void 0) {
          const err79 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_qualification" },
            message: "must have required property 'ontology_qualification'",
          };
          if (vErrors === null) {
            vErrors = [err79];
          } else {
            vErrors.push(err79);
          }
          errors++;
        }
        if (data50.agent_skills_lock === void 0) {
          const err80 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "agent_skills_lock" },
            message: "must have required property 'agent_skills_lock'",
          };
          if (vErrors === null) {
            vErrors = [err80];
          } else {
            vErrors.push(err80);
          }
          errors++;
        }
        if (data50.development === void 0) {
          const err81 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "development" },
            message: "must have required property 'development'",
          };
          if (vErrors === null) {
            vErrors = [err81];
          } else {
            vErrors.push(err81);
          }
          errors++;
        }
        if (data50.product_tests === void 0) {
          const err82 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "product_tests" },
            message: "must have required property 'product_tests'",
          };
          if (vErrors === null) {
            vErrors = [err82];
          } else {
            vErrors.push(err82);
          }
          errors++;
        }
        if (data50.ci_control === void 0) {
          const err83 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ci_control" },
            message: "must have required property 'ci_control'",
          };
          if (vErrors === null) {
            vErrors = [err83];
          } else {
            vErrors.push(err83);
          }
          errors++;
        }
        if (data50.mcp_artifacts === void 0) {
          const err84 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_artifacts" },
            message: "must have required property 'mcp_artifacts'",
          };
          if (vErrors === null) {
            vErrors = [err84];
          } else {
            vErrors.push(err84);
          }
          errors++;
        }
        if (data50.website_build === void 0) {
          const err85 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "website_build" },
            message: "must have required property 'website_build'",
          };
          if (vErrors === null) {
            vErrors = [err85];
          } else {
            vErrors.push(err85);
          }
          errors++;
        }
        if (data50.mcp_docs === void 0) {
          const err86 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_docs" },
            message: "must have required property 'mcp_docs'",
          };
          if (vErrors === null) {
            vErrors = [err86];
          } else {
            vErrors.push(err86);
          }
          errors++;
        }
        if (data50.mcp_application === void 0) {
          const err87 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_application" },
            message: "must have required property 'mcp_application'",
          };
          if (vErrors === null) {
            vErrors = [err87];
          } else {
            vErrors.push(err87);
          }
          errors++;
        }
        if (data50.mcp_release_qualification === void 0) {
          const err88 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_release_qualification" },
            message: "must have required property 'mcp_release_qualification'",
          };
          if (vErrors === null) {
            vErrors = [err88];
          } else {
            vErrors.push(err88);
          }
          errors++;
        }
        for (const key1 in data50) {
          if (!func1.call(schema31.properties.scopes.properties, key1)) {
            const err89 = {
              instancePath: instancePath + "/scopes",
              schemaPath: "#/properties/scopes/additionalProperties",
              keyword: "additionalProperties",
              params: { additionalProperty: key1 },
              message: "must NOT have additional properties",
            };
            if (vErrors === null) {
              vErrors = [err89];
            } else {
              vErrors.push(err89);
            }
            errors++;
          }
        }
        if (data50.style_tooling !== void 0) {
          if (typeof data50.style_tooling !== "boolean") {
            const err90 = {
              instancePath: instancePath + "/scopes/style_tooling",
              schemaPath: "#/properties/scopes/properties/style_tooling/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err90];
            } else {
              vErrors.push(err90);
            }
            errors++;
          }
        }
        if (data50.python_style !== void 0) {
          if (typeof data50.python_style !== "boolean") {
            const err91 = {
              instancePath: instancePath + "/scopes/python_style",
              schemaPath: "#/properties/scopes/properties/python_style/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err91];
            } else {
              vErrors.push(err91);
            }
            errors++;
          }
        }
        if (data50.python_tests !== void 0) {
          if (typeof data50.python_tests !== "boolean") {
            const err92 = {
              instancePath: instancePath + "/scopes/python_tests",
              schemaPath: "#/properties/scopes/properties/python_tests/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err92];
            } else {
              vErrors.push(err92);
            }
            errors++;
          }
        }
        if (data50.python_setup_tests !== void 0) {
          if (typeof data50.python_setup_tests !== "boolean") {
            const err93 = {
              instancePath: instancePath + "/scopes/python_setup_tests",
              schemaPath:
                "#/properties/scopes/properties/python_setup_tests/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err93];
            } else {
              vErrors.push(err93);
            }
            errors++;
          }
        }
        if (data50.documentation !== void 0) {
          if (typeof data50.documentation !== "boolean") {
            const err94 = {
              instancePath: instancePath + "/scopes/documentation",
              schemaPath: "#/properties/scopes/properties/documentation/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err94];
            } else {
              vErrors.push(err94);
            }
            errors++;
          }
        }
        if (data50.ontology_validation !== void 0) {
          if (typeof data50.ontology_validation !== "boolean") {
            const err95 = {
              instancePath: instancePath + "/scopes/ontology_validation",
              schemaPath:
                "#/properties/scopes/properties/ontology_validation/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err95];
            } else {
              vErrors.push(err95);
            }
            errors++;
          }
        }
        if (data50.ontology_validation_workflow !== void 0) {
          if (typeof data50.ontology_validation_workflow !== "boolean") {
            const err96 = {
              instancePath:
                instancePath + "/scopes/ontology_validation_workflow",
              schemaPath:
                "#/properties/scopes/properties/ontology_validation_workflow/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err96];
            } else {
              vErrors.push(err96);
            }
            errors++;
          }
        }
        if (data50.ontology_entity_contracts !== void 0) {
          if (typeof data50.ontology_entity_contracts !== "boolean") {
            const err97 = {
              instancePath: instancePath + "/scopes/ontology_entity_contracts",
              schemaPath:
                "#/properties/scopes/properties/ontology_entity_contracts/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err97];
            } else {
              vErrors.push(err97);
            }
            errors++;
          }
        }
        if (data50.ontology_policy_qa !== void 0) {
          if (typeof data50.ontology_policy_qa !== "boolean") {
            const err98 = {
              instancePath: instancePath + "/scopes/ontology_policy_qa",
              schemaPath:
                "#/properties/scopes/properties/ontology_policy_qa/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err98];
            } else {
              vErrors.push(err98);
            }
            errors++;
          }
        }
        if (data50.ontology_qualification !== void 0) {
          if (typeof data50.ontology_qualification !== "boolean") {
            const err99 = {
              instancePath: instancePath + "/scopes/ontology_qualification",
              schemaPath:
                "#/properties/scopes/properties/ontology_qualification/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err99];
            } else {
              vErrors.push(err99);
            }
            errors++;
          }
        }
        if (data50.agent_skills_lock !== void 0) {
          if (typeof data50.agent_skills_lock !== "boolean") {
            const err100 = {
              instancePath: instancePath + "/scopes/agent_skills_lock",
              schemaPath:
                "#/properties/scopes/properties/agent_skills_lock/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err100];
            } else {
              vErrors.push(err100);
            }
            errors++;
          }
        }
        if (data50.development !== void 0) {
          if (typeof data50.development !== "boolean") {
            const err101 = {
              instancePath: instancePath + "/scopes/development",
              schemaPath: "#/properties/scopes/properties/development/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err101];
            } else {
              vErrors.push(err101);
            }
            errors++;
          }
        }
        if (data50.product_tests !== void 0) {
          if (typeof data50.product_tests !== "boolean") {
            const err102 = {
              instancePath: instancePath + "/scopes/product_tests",
              schemaPath: "#/properties/scopes/properties/product_tests/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err102];
            } else {
              vErrors.push(err102);
            }
            errors++;
          }
        }
        if (data50.ci_control !== void 0) {
          if (typeof data50.ci_control !== "boolean") {
            const err103 = {
              instancePath: instancePath + "/scopes/ci_control",
              schemaPath: "#/properties/scopes/properties/ci_control/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err103];
            } else {
              vErrors.push(err103);
            }
            errors++;
          }
        }
        if (data50.mcp_artifacts !== void 0) {
          if (typeof data50.mcp_artifacts !== "boolean") {
            const err104 = {
              instancePath: instancePath + "/scopes/mcp_artifacts",
              schemaPath: "#/properties/scopes/properties/mcp_artifacts/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err104];
            } else {
              vErrors.push(err104);
            }
            errors++;
          }
        }
        if (data50.website_build !== void 0) {
          if (typeof data50.website_build !== "boolean") {
            const err105 = {
              instancePath: instancePath + "/scopes/website_build",
              schemaPath: "#/properties/scopes/properties/website_build/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err105];
            } else {
              vErrors.push(err105);
            }
            errors++;
          }
        }
        if (data50.mcp_docs !== void 0) {
          if (typeof data50.mcp_docs !== "boolean") {
            const err106 = {
              instancePath: instancePath + "/scopes/mcp_docs",
              schemaPath: "#/properties/scopes/properties/mcp_docs/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err106];
            } else {
              vErrors.push(err106);
            }
            errors++;
          }
        }
        if (data50.mcp_application !== void 0) {
          if (typeof data50.mcp_application !== "boolean") {
            const err107 = {
              instancePath: instancePath + "/scopes/mcp_application",
              schemaPath: "#/properties/scopes/properties/mcp_application/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err107];
            } else {
              vErrors.push(err107);
            }
            errors++;
          }
        }
        if (data50.mcp_release_qualification !== void 0) {
          if (typeof data50.mcp_release_qualification !== "boolean") {
            const err108 = {
              instancePath: instancePath + "/scopes/mcp_release_qualification",
              schemaPath:
                "#/properties/scopes/properties/mcp_release_qualification/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err108];
            } else {
              vErrors.push(err108);
            }
            errors++;
          }
        }
      } else {
        const err109 = {
          instancePath: instancePath + "/scopes",
          schemaPath: "#/properties/scopes/type",
          keyword: "type",
          params: { type: "object" },
          message: "must be object",
        };
        if (vErrors === null) {
          vErrors = [err109];
        } else {
          vErrors.push(err109);
        }
        errors++;
      }
    }
    if (data.requiredJobs !== void 0) {
      let data70 = data.requiredJobs;
      if (Array.isArray(data70)) {
        const len0 = data70.length;
        for (let i0 = 0; i0 < len0; i0++) {
          let data71 = data70[i0];
          if (!(
            data71 === "development" ||
            data71 === "ontology" ||
            data71 === "node" ||
            data71 === "website" ||
            data71 === "distribution"
          )) {
            const err110 = {
              instancePath: instancePath + "/requiredJobs/" + i0,
              schemaPath: "#/properties/requiredJobs/items/enum",
              keyword: "enum",
              params: {
                allowedValues: schema31.properties.requiredJobs.items.enum,
              },
              message: "must be equal to one of the allowed values",
            };
            if (vErrors === null) {
              vErrors = [err110];
            } else {
              vErrors.push(err110);
            }
            errors++;
          }
        }
        let i1 = data70.length;
        let j0;
        if (i1 > 1) {
          outer0: for (; i1--;) {
            for (j0 = i1; j0--;) {
              if (func0(data70[i1], data70[j0])) {
                const err111 = {
                  instancePath: instancePath + "/requiredJobs",
                  schemaPath: "#/properties/requiredJobs/uniqueItems",
                  keyword: "uniqueItems",
                  params: { i: i1, j: j0 },
                  message:
                    "must NOT have duplicate items (items ## " +
                    j0 +
                    " and " +
                    i1 +
                    " are identical)",
                };
                if (vErrors === null) {
                  vErrors = [err111];
                } else {
                  vErrors.push(err111);
                }
                errors++;
                break outer0;
              }
            }
          }
        }
      } else {
        const err112 = {
          instancePath: instancePath + "/requiredJobs",
          schemaPath: "#/properties/requiredJobs/type",
          keyword: "type",
          params: { type: "array" },
          message: "must be array",
        };
        if (vErrors === null) {
          vErrors = [err112];
        } else {
          vErrors.push(err112);
        }
        errors++;
      }
    }
  } else {
    const err113 = {
      instancePath,
      schemaPath: "#/type",
      keyword: "type",
      params: { type: "object" },
      message: "must be object",
    };
    if (vErrors === null) {
      vErrors = [err113];
    } else {
      vErrors.push(err113);
    }
    errors++;
  }
  validate20.errors = vErrors;
  return errors === 0;
}
validate20.evaluated = {
  props: true,
  dynamicProps: false,
  dynamicItems: false,
};
export { standalone_validator_default as default, validate };
