// Generated by generatePullRequestCheckPlanValidator.js; do not edit.
/* eslint-disable no-unused-vars, no-redeclare, no-useless-assignment -- Ajv emits shared signature fields and reusable validation temporaries. Schema and freshness tests govern this generated code. */
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) =>
  function __require() {
    try {
      return (
        mod ||
          (0, cb[__getOwnPropNames(cb)[0]])(
            (mod = { exports: {} }).exports,
            mod,
          ),
        mod.exports
      );
    } catch (e) {
      throw ((mod = 0), e);
    }
  };

// node_modules/fast-deep-equal/index.js
var require_fast_deep_equal = __commonJS({
  "node_modules/fast-deep-equal/index.js"(exports, module) {
    "use strict";
    module.exports = function equal(a, b) {
      if (a === b) return true;
      if (a && b && typeof a == "object" && typeof b == "object") {
        if (a.constructor !== b.constructor) return false;
        var length, i, keys;
        if (Array.isArray(a)) {
          length = a.length;
          if (length != b.length) return false;
          for (i = length; i-- !== 0;) if (!equal(a[i], b[i])) return false;
          return true;
        }
        if (a.constructor === RegExp)
          return a.source === b.source && a.flags === b.flags;
        if (a.valueOf !== Object.prototype.valueOf)
          return a.valueOf() === b.valueOf();
        if (a.toString !== Object.prototype.toString)
          return a.toString() === b.toString();
        keys = Object.keys(a);
        length = keys.length;
        if (length !== Object.keys(b).length) return false;
        for (i = length; i-- !== 0;)
          if (!Object.prototype.hasOwnProperty.call(b, keys[i])) return false;
        for (i = length; i-- !== 0;) {
          var key = keys[i];
          if (!equal(a[key], b[key])) return false;
        }
        return true;
      }
      return a !== a && b !== b;
    };
  },
});

// node_modules/ajv/dist/runtime/equal.js
var require_equal = __commonJS({
  "node_modules/ajv/dist/runtime/equal.js"(exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var equal = require_fast_deep_equal();
    equal.code = 'require("ajv/dist/runtime/equal").default';
    exports.default = equal;
  },
});

// standalone-validator.js
var validate = validate20;
var standalone_validator_default = validate20;
var schema31 = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  type: "object",
  additionalProperties: false,
  required: [
    "schemaVersion",
    "mode",
    "revision",
    "comparisonBase",
    "scopes",
    "requiredJobs",
  ],
  properties: {
    schemaVersion: { const: 1 },
    mode: { enum: ["changed", "full"] },
    revision: { type: "string", pattern: "^[a-f0-9]{40}$" },
    comparisonBase: {
      anyOf: [{ type: "null" }, { type: "string", pattern: "^[a-f0-9]{40}$" }],
    },
    scopes: {
      type: "object",
      additionalProperties: false,
      required: [
        "style_tooling",
        "python_style",
        "python_tests",
        "documentation",
        "ontology_validation",
        "ontology_validation_workflow",
        "ontology_entity_contracts",
        "ontology_policy_qa",
        "ontology_qualification",
        "agent_skills_lock",
        "development",
        "product_tests",
        "mcp_artifacts",
        "website_build",
        "mcp_docs",
        "mcp_application",
        "mcp_release_qualification",
      ],
      properties: {
        style_tooling: { type: "boolean" },
        python_style: { type: "boolean" },
        python_tests: { type: "boolean" },
        documentation: { type: "boolean" },
        ontology_validation: { type: "boolean" },
        ontology_validation_workflow: { type: "boolean" },
        ontology_entity_contracts: { type: "boolean" },
        ontology_policy_qa: { type: "boolean" },
        ontology_qualification: { type: "boolean" },
        agent_skills_lock: { type: "boolean" },
        development: { type: "boolean" },
        product_tests: { type: "boolean" },
        mcp_artifacts: { type: "boolean" },
        website_build: { type: "boolean" },
        mcp_docs: { type: "boolean" },
        mcp_application: { type: "boolean" },
        mcp_release_qualification: { type: "boolean" },
      },
    },
    requiredJobs: {
      type: "array",
      uniqueItems: true,
      items: {
        enum: ["development", "ontology", "node", "website", "distribution"],
      },
    },
  },
  allOf: [
    {
      if: { properties: { mode: { const: "changed" } } },
      then: {
        properties: {
          comparisonBase: { type: "string", pattern: "^[a-f0-9]{40}$" },
        },
      },
      else: {
        properties: {
          comparisonBase: { type: "null" },
          scopes: {
            properties: {
              style_tooling: { const: true },
              python_style: { const: true },
              python_tests: { const: true },
              documentation: { const: true },
              ontology_validation: { const: true },
              ontology_validation_workflow: { const: true },
              ontology_entity_contracts: { const: true },
              ontology_policy_qa: { const: true },
              ontology_qualification: { const: true },
              agent_skills_lock: { const: true },
              development: { const: true },
              product_tests: { const: true },
              mcp_artifacts: { const: true },
              website_build: { const: true },
              mcp_docs: { const: true },
              mcp_application: { const: true },
              mcp_release_qualification: { const: true },
            },
            type: "object",
          },
        },
      },
    },
  ],
};
var pattern4 = new RegExp("^[a-f0-9]{40}$", "u");
var func1 = Object.prototype.hasOwnProperty;
var func0 = require_equal().default;
function validate20(
  data,
  {
    instancePath = "",
    parentData,
    parentDataProperty,
    rootData = data,
    dynamicAnchors = {},
  } = {},
) {
  let vErrors = null;
  let errors = 0;
  const evaluated0 = validate20.evaluated;
  if (evaluated0.dynamicProps) {
    evaluated0.props = void 0;
  }
  if (evaluated0.dynamicItems) {
    evaluated0.items = void 0;
  }
  const _errs2 = errors;
  let valid1 = true;
  const _errs3 = errors;
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.mode !== void 0) {
      if ("changed" !== data.mode) {
        const err0 = {};
        if (vErrors === null) {
          vErrors = [err0];
        } else {
          vErrors.push(err0);
        }
        errors++;
      }
    }
  }
  var _valid0 = _errs3 === errors;
  errors = _errs2;
  if (vErrors !== null) {
    if (_errs2) {
      vErrors.length = _errs2;
    } else {
      vErrors = null;
    }
  }
  let ifClause0;
  if (_valid0) {
    const _errs5 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.comparisonBase !== void 0) {
        let data1 = data.comparisonBase;
        if (typeof data1 === "string") {
          if (!pattern4.test(data1)) {
            const err1 = {
              instancePath: instancePath + "/comparisonBase",
              schemaPath: "#/allOf/0/then/properties/comparisonBase/pattern",
              keyword: "pattern",
              params: { pattern: "^[a-f0-9]{40}$" },
              message: 'must match pattern "^[a-f0-9]{40}$"',
            };
            if (vErrors === null) {
              vErrors = [err1];
            } else {
              vErrors.push(err1);
            }
            errors++;
          }
        } else {
          const err2 = {
            instancePath: instancePath + "/comparisonBase",
            schemaPath: "#/allOf/0/then/properties/comparisonBase/type",
            keyword: "type",
            params: { type: "string" },
            message: "must be string",
          };
          if (vErrors === null) {
            vErrors = [err2];
          } else {
            vErrors.push(err2);
          }
          errors++;
        }
      }
    }
    var _valid0 = _errs5 === errors;
    valid1 = _valid0;
    if (valid1) {
      var props0 = {};
      props0.comparisonBase = true;
      props0.mode = true;
    }
    ifClause0 = "then";
  } else {
    const _errs8 = errors;
    if (data && typeof data == "object" && !Array.isArray(data)) {
      if (data.comparisonBase !== void 0) {
        if (data.comparisonBase !== null) {
          const err3 = {
            instancePath: instancePath + "/comparisonBase",
            schemaPath: "#/allOf/0/else/properties/comparisonBase/type",
            keyword: "type",
            params: { type: "null" },
            message: "must be null",
          };
          if (vErrors === null) {
            vErrors = [err3];
          } else {
            vErrors.push(err3);
          }
          errors++;
        }
      }
      if (data.scopes !== void 0) {
        let data3 = data.scopes;
        if (data3 && typeof data3 == "object" && !Array.isArray(data3)) {
          if (data3.style_tooling !== void 0) {
            if (true !== data3.style_tooling) {
              const err4 = {
                instancePath: instancePath + "/scopes/style_tooling",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/style_tooling/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err4];
              } else {
                vErrors.push(err4);
              }
              errors++;
            }
          }
          if (data3.python_style !== void 0) {
            if (true !== data3.python_style) {
              const err5 = {
                instancePath: instancePath + "/scopes/python_style",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/python_style/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err5];
              } else {
                vErrors.push(err5);
              }
              errors++;
            }
          }
          if (data3.python_tests !== void 0) {
            if (true !== data3.python_tests) {
              const err6 = {
                instancePath: instancePath + "/scopes/python_tests",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/python_tests/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err6];
              } else {
                vErrors.push(err6);
              }
              errors++;
            }
          }
          if (data3.documentation !== void 0) {
            if (true !== data3.documentation) {
              const err7 = {
                instancePath: instancePath + "/scopes/documentation",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/documentation/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err7];
              } else {
                vErrors.push(err7);
              }
              errors++;
            }
          }
          if (data3.ontology_validation !== void 0) {
            if (true !== data3.ontology_validation) {
              const err8 = {
                instancePath: instancePath + "/scopes/ontology_validation",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_validation/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err8];
              } else {
                vErrors.push(err8);
              }
              errors++;
            }
          }
          if (data3.ontology_validation_workflow !== void 0) {
            if (true !== data3.ontology_validation_workflow) {
              const err9 = {
                instancePath:
                  instancePath + "/scopes/ontology_validation_workflow",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_validation_workflow/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err9];
              } else {
                vErrors.push(err9);
              }
              errors++;
            }
          }
          if (data3.ontology_entity_contracts !== void 0) {
            if (true !== data3.ontology_entity_contracts) {
              const err10 = {
                instancePath:
                  instancePath + "/scopes/ontology_entity_contracts",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_entity_contracts/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err10];
              } else {
                vErrors.push(err10);
              }
              errors++;
            }
          }
          if (data3.ontology_policy_qa !== void 0) {
            if (true !== data3.ontology_policy_qa) {
              const err11 = {
                instancePath: instancePath + "/scopes/ontology_policy_qa",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_policy_qa/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err11];
              } else {
                vErrors.push(err11);
              }
              errors++;
            }
          }
          if (data3.ontology_qualification !== void 0) {
            if (true !== data3.ontology_qualification) {
              const err12 = {
                instancePath: instancePath + "/scopes/ontology_qualification",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/ontology_qualification/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err12];
              } else {
                vErrors.push(err12);
              }
              errors++;
            }
          }
          if (data3.agent_skills_lock !== void 0) {
            if (true !== data3.agent_skills_lock) {
              const err13 = {
                instancePath: instancePath + "/scopes/agent_skills_lock",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/agent_skills_lock/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err13];
              } else {
                vErrors.push(err13);
              }
              errors++;
            }
          }
          if (data3.development !== void 0) {
            if (true !== data3.development) {
              const err14 = {
                instancePath: instancePath + "/scopes/development",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/development/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err14];
              } else {
                vErrors.push(err14);
              }
              errors++;
            }
          }
          if (data3.product_tests !== void 0) {
            if (true !== data3.product_tests) {
              const err15 = {
                instancePath: instancePath + "/scopes/product_tests",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/product_tests/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err15];
              } else {
                vErrors.push(err15);
              }
              errors++;
            }
          }
          if (data3.mcp_artifacts !== void 0) {
            if (true !== data3.mcp_artifacts) {
              const err16 = {
                instancePath: instancePath + "/scopes/mcp_artifacts",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/mcp_artifacts/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err16];
              } else {
                vErrors.push(err16);
              }
              errors++;
            }
          }
          if (data3.website_build !== void 0) {
            if (true !== data3.website_build) {
              const err17 = {
                instancePath: instancePath + "/scopes/website_build",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/website_build/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err17];
              } else {
                vErrors.push(err17);
              }
              errors++;
            }
          }
          if (data3.mcp_docs !== void 0) {
            if (true !== data3.mcp_docs) {
              const err18 = {
                instancePath: instancePath + "/scopes/mcp_docs",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/mcp_docs/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err18];
              } else {
                vErrors.push(err18);
              }
              errors++;
            }
          }
          if (data3.mcp_application !== void 0) {
            if (true !== data3.mcp_application) {
              const err19 = {
                instancePath: instancePath + "/scopes/mcp_application",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/mcp_application/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err19];
              } else {
                vErrors.push(err19);
              }
              errors++;
            }
          }
          if (data3.mcp_release_qualification !== void 0) {
            if (true !== data3.mcp_release_qualification) {
              const err20 = {
                instancePath:
                  instancePath + "/scopes/mcp_release_qualification",
                schemaPath:
                  "#/allOf/0/else/properties/scopes/properties/mcp_release_qualification/const",
                keyword: "const",
                params: { allowedValue: true },
                message: "must be equal to constant",
              };
              if (vErrors === null) {
                vErrors = [err20];
              } else {
                vErrors.push(err20);
              }
              errors++;
            }
          }
        } else {
          const err21 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/allOf/0/else/properties/scopes/type",
            keyword: "type",
            params: { type: "object" },
            message: "must be object",
          };
          if (vErrors === null) {
            vErrors = [err21];
          } else {
            vErrors.push(err21);
          }
          errors++;
        }
      }
    }
    var _valid0 = _errs8 === errors;
    valid1 = _valid0;
    if (valid1) {
      if (props0 !== true) {
        props0 = props0 || {};
        props0.comparisonBase = true;
        props0.scopes = true;
      }
    }
    ifClause0 = "else";
  }
  if (!valid1) {
    const err22 = {
      instancePath,
      schemaPath: "#/allOf/0/if",
      keyword: "if",
      params: { failingKeyword: ifClause0 },
      message: 'must match "' + ifClause0 + '" schema',
    };
    if (vErrors === null) {
      vErrors = [err22];
    } else {
      vErrors.push(err22);
    }
    errors++;
  }
  if (data && typeof data == "object" && !Array.isArray(data)) {
    if (data.schemaVersion === void 0) {
      const err23 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "schemaVersion" },
        message: "must have required property 'schemaVersion'",
      };
      if (vErrors === null) {
        vErrors = [err23];
      } else {
        vErrors.push(err23);
      }
      errors++;
    }
    if (data.mode === void 0) {
      const err24 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "mode" },
        message: "must have required property 'mode'",
      };
      if (vErrors === null) {
        vErrors = [err24];
      } else {
        vErrors.push(err24);
      }
      errors++;
    }
    if (data.revision === void 0) {
      const err25 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "revision" },
        message: "must have required property 'revision'",
      };
      if (vErrors === null) {
        vErrors = [err25];
      } else {
        vErrors.push(err25);
      }
      errors++;
    }
    if (data.comparisonBase === void 0) {
      const err26 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "comparisonBase" },
        message: "must have required property 'comparisonBase'",
      };
      if (vErrors === null) {
        vErrors = [err26];
      } else {
        vErrors.push(err26);
      }
      errors++;
    }
    if (data.scopes === void 0) {
      const err27 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "scopes" },
        message: "must have required property 'scopes'",
      };
      if (vErrors === null) {
        vErrors = [err27];
      } else {
        vErrors.push(err27);
      }
      errors++;
    }
    if (data.requiredJobs === void 0) {
      const err28 = {
        instancePath,
        schemaPath: "#/required",
        keyword: "required",
        params: { missingProperty: "requiredJobs" },
        message: "must have required property 'requiredJobs'",
      };
      if (vErrors === null) {
        vErrors = [err28];
      } else {
        vErrors.push(err28);
      }
      errors++;
    }
    for (const key0 in data) {
      if (!(
        key0 === "schemaVersion" ||
        key0 === "mode" ||
        key0 === "revision" ||
        key0 === "comparisonBase" ||
        key0 === "scopes" ||
        key0 === "requiredJobs"
      )) {
        const err29 = {
          instancePath,
          schemaPath: "#/additionalProperties",
          keyword: "additionalProperties",
          params: { additionalProperty: key0 },
          message: "must NOT have additional properties",
        };
        if (vErrors === null) {
          vErrors = [err29];
        } else {
          vErrors.push(err29);
        }
        errors++;
      }
    }
    if (data.schemaVersion !== void 0) {
      if (1 !== data.schemaVersion) {
        const err30 = {
          instancePath: instancePath + "/schemaVersion",
          schemaPath: "#/properties/schemaVersion/const",
          keyword: "const",
          params: { allowedValue: 1 },
          message: "must be equal to constant",
        };
        if (vErrors === null) {
          vErrors = [err30];
        } else {
          vErrors.push(err30);
        }
        errors++;
      }
    }
    if (data.mode !== void 0) {
      let data22 = data.mode;
      if (!(data22 === "changed" || data22 === "full")) {
        const err31 = {
          instancePath: instancePath + "/mode",
          schemaPath: "#/properties/mode/enum",
          keyword: "enum",
          params: { allowedValues: schema31.properties.mode.enum },
          message: "must be equal to one of the allowed values",
        };
        if (vErrors === null) {
          vErrors = [err31];
        } else {
          vErrors.push(err31);
        }
        errors++;
      }
    }
    if (data.revision !== void 0) {
      let data23 = data.revision;
      if (typeof data23 === "string") {
        if (!pattern4.test(data23)) {
          const err32 = {
            instancePath: instancePath + "/revision",
            schemaPath: "#/properties/revision/pattern",
            keyword: "pattern",
            params: { pattern: "^[a-f0-9]{40}$" },
            message: 'must match pattern "^[a-f0-9]{40}$"',
          };
          if (vErrors === null) {
            vErrors = [err32];
          } else {
            vErrors.push(err32);
          }
          errors++;
        }
      } else {
        const err33 = {
          instancePath: instancePath + "/revision",
          schemaPath: "#/properties/revision/type",
          keyword: "type",
          params: { type: "string" },
          message: "must be string",
        };
        if (vErrors === null) {
          vErrors = [err33];
        } else {
          vErrors.push(err33);
        }
        errors++;
      }
    }
    if (data.comparisonBase !== void 0) {
      let data24 = data.comparisonBase;
      const _errs36 = errors;
      let valid7 = false;
      const _errs37 = errors;
      if (data24 !== null) {
        const err34 = {
          instancePath: instancePath + "/comparisonBase",
          schemaPath: "#/properties/comparisonBase/anyOf/0/type",
          keyword: "type",
          params: { type: "null" },
          message: "must be null",
        };
        if (vErrors === null) {
          vErrors = [err34];
        } else {
          vErrors.push(err34);
        }
        errors++;
      }
      var _valid1 = _errs37 === errors;
      valid7 = valid7 || _valid1;
      const _errs39 = errors;
      if (typeof data24 === "string") {
        if (!pattern4.test(data24)) {
          const err35 = {
            instancePath: instancePath + "/comparisonBase",
            schemaPath: "#/properties/comparisonBase/anyOf/1/pattern",
            keyword: "pattern",
            params: { pattern: "^[a-f0-9]{40}$" },
            message: 'must match pattern "^[a-f0-9]{40}$"',
          };
          if (vErrors === null) {
            vErrors = [err35];
          } else {
            vErrors.push(err35);
          }
          errors++;
        }
      } else {
        const err36 = {
          instancePath: instancePath + "/comparisonBase",
          schemaPath: "#/properties/comparisonBase/anyOf/1/type",
          keyword: "type",
          params: { type: "string" },
          message: "must be string",
        };
        if (vErrors === null) {
          vErrors = [err36];
        } else {
          vErrors.push(err36);
        }
        errors++;
      }
      var _valid1 = _errs39 === errors;
      valid7 = valid7 || _valid1;
      if (!valid7) {
        const err37 = {
          instancePath: instancePath + "/comparisonBase",
          schemaPath: "#/properties/comparisonBase/anyOf",
          keyword: "anyOf",
          params: {},
          message: "must match a schema in anyOf",
        };
        if (vErrors === null) {
          vErrors = [err37];
        } else {
          vErrors.push(err37);
        }
        errors++;
      } else {
        errors = _errs36;
        if (vErrors !== null) {
          if (_errs36) {
            vErrors.length = _errs36;
          } else {
            vErrors = null;
          }
        }
      }
    }
    if (data.scopes !== void 0) {
      let data25 = data.scopes;
      if (data25 && typeof data25 == "object" && !Array.isArray(data25)) {
        if (data25.style_tooling === void 0) {
          const err38 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "style_tooling" },
            message: "must have required property 'style_tooling'",
          };
          if (vErrors === null) {
            vErrors = [err38];
          } else {
            vErrors.push(err38);
          }
          errors++;
        }
        if (data25.python_style === void 0) {
          const err39 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "python_style" },
            message: "must have required property 'python_style'",
          };
          if (vErrors === null) {
            vErrors = [err39];
          } else {
            vErrors.push(err39);
          }
          errors++;
        }
        if (data25.python_tests === void 0) {
          const err40 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "python_tests" },
            message: "must have required property 'python_tests'",
          };
          if (vErrors === null) {
            vErrors = [err40];
          } else {
            vErrors.push(err40);
          }
          errors++;
        }
        if (data25.documentation === void 0) {
          const err41 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "documentation" },
            message: "must have required property 'documentation'",
          };
          if (vErrors === null) {
            vErrors = [err41];
          } else {
            vErrors.push(err41);
          }
          errors++;
        }
        if (data25.ontology_validation === void 0) {
          const err42 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_validation" },
            message: "must have required property 'ontology_validation'",
          };
          if (vErrors === null) {
            vErrors = [err42];
          } else {
            vErrors.push(err42);
          }
          errors++;
        }
        if (data25.ontology_validation_workflow === void 0) {
          const err43 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_validation_workflow" },
            message:
              "must have required property 'ontology_validation_workflow'",
          };
          if (vErrors === null) {
            vErrors = [err43];
          } else {
            vErrors.push(err43);
          }
          errors++;
        }
        if (data25.ontology_entity_contracts === void 0) {
          const err44 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_entity_contracts" },
            message: "must have required property 'ontology_entity_contracts'",
          };
          if (vErrors === null) {
            vErrors = [err44];
          } else {
            vErrors.push(err44);
          }
          errors++;
        }
        if (data25.ontology_policy_qa === void 0) {
          const err45 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_policy_qa" },
            message: "must have required property 'ontology_policy_qa'",
          };
          if (vErrors === null) {
            vErrors = [err45];
          } else {
            vErrors.push(err45);
          }
          errors++;
        }
        if (data25.ontology_qualification === void 0) {
          const err46 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "ontology_qualification" },
            message: "must have required property 'ontology_qualification'",
          };
          if (vErrors === null) {
            vErrors = [err46];
          } else {
            vErrors.push(err46);
          }
          errors++;
        }
        if (data25.agent_skills_lock === void 0) {
          const err47 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "agent_skills_lock" },
            message: "must have required property 'agent_skills_lock'",
          };
          if (vErrors === null) {
            vErrors = [err47];
          } else {
            vErrors.push(err47);
          }
          errors++;
        }
        if (data25.development === void 0) {
          const err48 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "development" },
            message: "must have required property 'development'",
          };
          if (vErrors === null) {
            vErrors = [err48];
          } else {
            vErrors.push(err48);
          }
          errors++;
        }
        if (data25.product_tests === void 0) {
          const err49 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "product_tests" },
            message: "must have required property 'product_tests'",
          };
          if (vErrors === null) {
            vErrors = [err49];
          } else {
            vErrors.push(err49);
          }
          errors++;
        }
        if (data25.mcp_artifacts === void 0) {
          const err50 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_artifacts" },
            message: "must have required property 'mcp_artifacts'",
          };
          if (vErrors === null) {
            vErrors = [err50];
          } else {
            vErrors.push(err50);
          }
          errors++;
        }
        if (data25.website_build === void 0) {
          const err51 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "website_build" },
            message: "must have required property 'website_build'",
          };
          if (vErrors === null) {
            vErrors = [err51];
          } else {
            vErrors.push(err51);
          }
          errors++;
        }
        if (data25.mcp_docs === void 0) {
          const err52 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_docs" },
            message: "must have required property 'mcp_docs'",
          };
          if (vErrors === null) {
            vErrors = [err52];
          } else {
            vErrors.push(err52);
          }
          errors++;
        }
        if (data25.mcp_application === void 0) {
          const err53 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_application" },
            message: "must have required property 'mcp_application'",
          };
          if (vErrors === null) {
            vErrors = [err53];
          } else {
            vErrors.push(err53);
          }
          errors++;
        }
        if (data25.mcp_release_qualification === void 0) {
          const err54 = {
            instancePath: instancePath + "/scopes",
            schemaPath: "#/properties/scopes/required",
            keyword: "required",
            params: { missingProperty: "mcp_release_qualification" },
            message: "must have required property 'mcp_release_qualification'",
          };
          if (vErrors === null) {
            vErrors = [err54];
          } else {
            vErrors.push(err54);
          }
          errors++;
        }
        for (const key1 in data25) {
          if (!func1.call(schema31.properties.scopes.properties, key1)) {
            const err55 = {
              instancePath: instancePath + "/scopes",
              schemaPath: "#/properties/scopes/additionalProperties",
              keyword: "additionalProperties",
              params: { additionalProperty: key1 },
              message: "must NOT have additional properties",
            };
            if (vErrors === null) {
              vErrors = [err55];
            } else {
              vErrors.push(err55);
            }
            errors++;
          }
        }
        if (data25.style_tooling !== void 0) {
          if (typeof data25.style_tooling !== "boolean") {
            const err56 = {
              instancePath: instancePath + "/scopes/style_tooling",
              schemaPath: "#/properties/scopes/properties/style_tooling/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err56];
            } else {
              vErrors.push(err56);
            }
            errors++;
          }
        }
        if (data25.python_style !== void 0) {
          if (typeof data25.python_style !== "boolean") {
            const err57 = {
              instancePath: instancePath + "/scopes/python_style",
              schemaPath: "#/properties/scopes/properties/python_style/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err57];
            } else {
              vErrors.push(err57);
            }
            errors++;
          }
        }
        if (data25.python_tests !== void 0) {
          if (typeof data25.python_tests !== "boolean") {
            const err58 = {
              instancePath: instancePath + "/scopes/python_tests",
              schemaPath: "#/properties/scopes/properties/python_tests/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err58];
            } else {
              vErrors.push(err58);
            }
            errors++;
          }
        }
        if (data25.documentation !== void 0) {
          if (typeof data25.documentation !== "boolean") {
            const err59 = {
              instancePath: instancePath + "/scopes/documentation",
              schemaPath: "#/properties/scopes/properties/documentation/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err59];
            } else {
              vErrors.push(err59);
            }
            errors++;
          }
        }
        if (data25.ontology_validation !== void 0) {
          if (typeof data25.ontology_validation !== "boolean") {
            const err60 = {
              instancePath: instancePath + "/scopes/ontology_validation",
              schemaPath:
                "#/properties/scopes/properties/ontology_validation/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err60];
            } else {
              vErrors.push(err60);
            }
            errors++;
          }
        }
        if (data25.ontology_validation_workflow !== void 0) {
          if (typeof data25.ontology_validation_workflow !== "boolean") {
            const err61 = {
              instancePath:
                instancePath + "/scopes/ontology_validation_workflow",
              schemaPath:
                "#/properties/scopes/properties/ontology_validation_workflow/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err61];
            } else {
              vErrors.push(err61);
            }
            errors++;
          }
        }
        if (data25.ontology_entity_contracts !== void 0) {
          if (typeof data25.ontology_entity_contracts !== "boolean") {
            const err62 = {
              instancePath: instancePath + "/scopes/ontology_entity_contracts",
              schemaPath:
                "#/properties/scopes/properties/ontology_entity_contracts/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err62];
            } else {
              vErrors.push(err62);
            }
            errors++;
          }
        }
        if (data25.ontology_policy_qa !== void 0) {
          if (typeof data25.ontology_policy_qa !== "boolean") {
            const err63 = {
              instancePath: instancePath + "/scopes/ontology_policy_qa",
              schemaPath:
                "#/properties/scopes/properties/ontology_policy_qa/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err63];
            } else {
              vErrors.push(err63);
            }
            errors++;
          }
        }
        if (data25.ontology_qualification !== void 0) {
          if (typeof data25.ontology_qualification !== "boolean") {
            const err64 = {
              instancePath: instancePath + "/scopes/ontology_qualification",
              schemaPath:
                "#/properties/scopes/properties/ontology_qualification/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err64];
            } else {
              vErrors.push(err64);
            }
            errors++;
          }
        }
        if (data25.agent_skills_lock !== void 0) {
          if (typeof data25.agent_skills_lock !== "boolean") {
            const err65 = {
              instancePath: instancePath + "/scopes/agent_skills_lock",
              schemaPath:
                "#/properties/scopes/properties/agent_skills_lock/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err65];
            } else {
              vErrors.push(err65);
            }
            errors++;
          }
        }
        if (data25.development !== void 0) {
          if (typeof data25.development !== "boolean") {
            const err66 = {
              instancePath: instancePath + "/scopes/development",
              schemaPath: "#/properties/scopes/properties/development/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err66];
            } else {
              vErrors.push(err66);
            }
            errors++;
          }
        }
        if (data25.product_tests !== void 0) {
          if (typeof data25.product_tests !== "boolean") {
            const err67 = {
              instancePath: instancePath + "/scopes/product_tests",
              schemaPath: "#/properties/scopes/properties/product_tests/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err67];
            } else {
              vErrors.push(err67);
            }
            errors++;
          }
        }
        if (data25.mcp_artifacts !== void 0) {
          if (typeof data25.mcp_artifacts !== "boolean") {
            const err68 = {
              instancePath: instancePath + "/scopes/mcp_artifacts",
              schemaPath: "#/properties/scopes/properties/mcp_artifacts/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err68];
            } else {
              vErrors.push(err68);
            }
            errors++;
          }
        }
        if (data25.website_build !== void 0) {
          if (typeof data25.website_build !== "boolean") {
            const err69 = {
              instancePath: instancePath + "/scopes/website_build",
              schemaPath: "#/properties/scopes/properties/website_build/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err69];
            } else {
              vErrors.push(err69);
            }
            errors++;
          }
        }
        if (data25.mcp_docs !== void 0) {
          if (typeof data25.mcp_docs !== "boolean") {
            const err70 = {
              instancePath: instancePath + "/scopes/mcp_docs",
              schemaPath: "#/properties/scopes/properties/mcp_docs/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err70];
            } else {
              vErrors.push(err70);
            }
            errors++;
          }
        }
        if (data25.mcp_application !== void 0) {
          if (typeof data25.mcp_application !== "boolean") {
            const err71 = {
              instancePath: instancePath + "/scopes/mcp_application",
              schemaPath: "#/properties/scopes/properties/mcp_application/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err71];
            } else {
              vErrors.push(err71);
            }
            errors++;
          }
        }
        if (data25.mcp_release_qualification !== void 0) {
          if (typeof data25.mcp_release_qualification !== "boolean") {
            const err72 = {
              instancePath: instancePath + "/scopes/mcp_release_qualification",
              schemaPath:
                "#/properties/scopes/properties/mcp_release_qualification/type",
              keyword: "type",
              params: { type: "boolean" },
              message: "must be boolean",
            };
            if (vErrors === null) {
              vErrors = [err72];
            } else {
              vErrors.push(err72);
            }
            errors++;
          }
        }
      } else {
        const err73 = {
          instancePath: instancePath + "/scopes",
          schemaPath: "#/properties/scopes/type",
          keyword: "type",
          params: { type: "object" },
          message: "must be object",
        };
        if (vErrors === null) {
          vErrors = [err73];
        } else {
          vErrors.push(err73);
        }
        errors++;
      }
    }
    if (data.requiredJobs !== void 0) {
      let data43 = data.requiredJobs;
      if (Array.isArray(data43)) {
        const len0 = data43.length;
        for (let i0 = 0; i0 < len0; i0++) {
          let data44 = data43[i0];
          if (!(
            data44 === "development" ||
            data44 === "ontology" ||
            data44 === "node" ||
            data44 === "website" ||
            data44 === "distribution"
          )) {
            const err74 = {
              instancePath: instancePath + "/requiredJobs/" + i0,
              schemaPath: "#/properties/requiredJobs/items/enum",
              keyword: "enum",
              params: {
                allowedValues: schema31.properties.requiredJobs.items.enum,
              },
              message: "must be equal to one of the allowed values",
            };
            if (vErrors === null) {
              vErrors = [err74];
            } else {
              vErrors.push(err74);
            }
            errors++;
          }
        }
        let i1 = data43.length;
        let j0;
        if (i1 > 1) {
          outer0: for (; i1--;) {
            for (j0 = i1; j0--;) {
              if (func0(data43[i1], data43[j0])) {
                const err75 = {
                  instancePath: instancePath + "/requiredJobs",
                  schemaPath: "#/properties/requiredJobs/uniqueItems",
                  keyword: "uniqueItems",
                  params: { i: i1, j: j0 },
                  message:
                    "must NOT have duplicate items (items ## " +
                    j0 +
                    " and " +
                    i1 +
                    " are identical)",
                };
                if (vErrors === null) {
                  vErrors = [err75];
                } else {
                  vErrors.push(err75);
                }
                errors++;
                break outer0;
              }
            }
          }
        }
      } else {
        const err76 = {
          instancePath: instancePath + "/requiredJobs",
          schemaPath: "#/properties/requiredJobs/type",
          keyword: "type",
          params: { type: "array" },
          message: "must be array",
        };
        if (vErrors === null) {
          vErrors = [err76];
        } else {
          vErrors.push(err76);
        }
        errors++;
      }
    }
  } else {
    const err77 = {
      instancePath,
      schemaPath: "#/type",
      keyword: "type",
      params: { type: "object" },
      message: "must be object",
    };
    if (vErrors === null) {
      vErrors = [err77];
    } else {
      vErrors.push(err77);
    }
    errors++;
  }
  validate20.errors = vErrors;
  return errors === 0;
}
validate20.evaluated = {
  props: true,
  dynamicProps: false,
  dynamicItems: false,
};
export { standalone_validator_default as default, validate };
