import { afterEach, expect, test } from "@jest/globals";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { OWLManager } from "owlapi/apibinding";
import {
  OWLOntologyLoaderConfiguration,
  OWLOntologyWriterConfiguration,
} from "owlapi/model";
import { StringDocumentSource } from "owlapi/io";
import { OWLDocumentFormats } from "owlapi/formats";
import { materializeImportClosure } from "../../scripts/materializeImportClosure.js";
import { writeVerifiedOntology } from "../../scripts/ontology/atomicOntologyWriter.js";

const directories = [];
afterEach(async () => {
  await Promise.all(
    directories.splice(0).map((path) => rm(path, { recursive: true })),
  );
});

test("materializes a readable RDF/XML closure with the producer defaults", async () => {
  const directory = await mkdtemp(join(tmpdir(), "uo-readable-rdfxml-"));
  directories.push(directory);
  const inputPath = join(directory, "root.ofn");
  const modulePath = join(directory, "module.ofn");
  const outputPath = join(directory, "root-full");
  const prefix = "https://example.test/vocabulary#";
  await writeFile(
    modulePath,
    `Prefix(:=<${prefix}>)
Ontology(<https://example.test/module>
  Declaration(Class(:Imported))
  Declaration(Class(:Base))
  SubClassOf(:Imported :Base)
)`,
  );
  await writeFile(
    inputPath,
    `Prefix(:=<${prefix}>)
Ontology(<https://example.test/root> <https://example.test/root/v1>
  Import(<${pathToFileURL(modulePath).href}>)
  Annotation(<http://www.w3.org/2000/01/rdf-schema#label> "Root label")
  Declaration(Class(:Root))
  Declaration(ObjectProperty(:hasPart))
  SubClassOf(:Root ObjectSomeValuesFrom(:hasPart :Imported))
)`,
  );

  await materializeImportClosure({ inputPath, outputPath });
  const text = await readFile(outputPath, "utf8");
  expect(text).toContain(
    '<owl:Ontology rdf:about="https://example.test/root">',
  );
  for (const name of ["Root", "Imported", "Base"])
    expect(text).toContain(`<owl:Class rdf:about="${prefix}${name}"`);
  expect(text).toContain(`<owl:ObjectProperty rdf:about="${prefix}hasPart"`);
  expect(text).toMatch(/<owl:Restriction(?:\s[^>]*)?>/u);
  expect(text).toMatch(/<rdfs:label(?:\s[^>]*)?>Root label<\/rdfs:label>/u);
  expect(text).toMatch(/^ {4}<owl:Class /mu);
  expect(text).toMatch(/^ {8}<rdfs:subClassOf>/mu);
  expect(text).not.toContain("<owl:imports");
  expect(text).not.toContain("Generated by the OWL API (version");

  // Validate the actual published file with acquisition prohibited. The
  // independently authored fixture contains six direct axioms after collapse.
  const manager = OWLManager.createOWLOntologyManager({
    documentLoader: {
      load() {
        throw new Error("The generated closure must be standalone");
      },
    },
  });
  const ontology = await manager.loadOntologyFromOntologyDocument(
    new StringDocumentSource(text, { format: OWLDocumentFormats.RDF_XML }),
    new OWLOntologyLoaderConfiguration({
      format: OWLDocumentFormats.RDF_XML,
      parsingMode: "strict",
      remoteImports: false,
    }),
  );
  expect(ontology.getOntologyID().ontologyIRI.value).toBe(
    "https://example.test/root",
  );
  expect(ontology.getOntologyID().versionIRI.value).toBe(
    "https://example.test/root/v1",
  );
  expect(ontology.getAxioms().size).toBe(6);
  expect(ontology.getAnnotations().size).toBe(1);
  expect(ontology.getImportsDeclarations().size).toBe(0);
  expect(manager.getImportsClosure(ontology).size).toBe(1);
});

test("copies only the authored RDF/XML root prefix preferences into the closure", async () => {
  const directory = await mkdtemp(join(tmpdir(), "uo-root-prefixes-"));
  directories.push(directory);
  const inputPath = join(directory, "root.rdf");
  const modulePath = join(directory, "module.rdf");
  const outputPath = join(directory, "root-full");
  await writeFile(
    modulePath,
    `<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
      xmlns:owl="http://www.w3.org/2002/07/owl#"
      xmlns:chosen="https://example.test/imported#"
      xmlns:importOnly="https://example.test/import-only-unused#">
      <owl:Ontology rdf:about="https://example.test/module"/>
      <owl:Class rdf:about="https://example.test/module#Imported"/>
    </rdf:RDF>`,
  );
  await writeFile(
    inputPath,
    `<rdf:RDF xmlns="urn:authored:root#" xml:base="urn:authored:root"
      xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
      xmlns:owl="http://www.w3.org/2002/07/owl#"
      xmlns:chosen="https://example.test/authored#"
      xmlns:unused="https://example.test/root-unused#">
      <owl:Ontology rdf:about="https://example.test/root">
        <owl:imports rdf:resource="${pathToFileURL(modulePath).href}"/>
        <chosen:note>Root annotation</chosen:note>
      </owl:Ontology>
      <owl:AnnotationProperty rdf:about="https://example.test/authored#note"/>
      <owl:Class rdf:about="urn:authored:root#Root"/>
    </rdf:RDF>`,
  );
  await materializeImportClosure({ inputPath, outputPath });
  const text = await readFile(outputPath, "utf8");
  expect(text).toContain('xmlns="urn:authored:root#"');
  expect(text).toContain('xml:base="urn:authored:root"');
  expect(text).toContain('xmlns:chosen="https://example.test/authored#"');
  expect(text).toContain('xmlns:unused="https://example.test/root-unused#"');
  expect(text).not.toContain("xmlns:importOnly=");
  expect(text).not.toContain('xmlns:chosen="https://example.test/imported#"');
  expect(text).toContain("<chosen:note>Root annotation</chosen:note>");
  expect(text).toContain('rdf:about="https://example.test/module#Imported"');
  expect(text).not.toContain("<owl:imports");
});

test.each(["not an IRI", "relative"])(
  "reports invalid unused namespace %s as a serialization failure without replacing the target",
  async (namespace) => {
    const directory = await mkdtemp(join(tmpdir(), "uo-prefix-failure-"));
    directories.push(directory);
    const inputPath = join(directory, "root.rdf");
    const outputPath = join(directory, "root-full");
    await writeFile(
      inputPath,
      `<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:unused="${namespace}">
        <owl:Ontology rdf:about="https://example.test/root"/>
      </rdf:RDF>`,
    );
    await writeFile(outputPath, "previous verified target");
    await expect(
      materializeImportClosure({ inputPath, outputPath }),
    ).rejects.toMatchObject({
      stage: "serialization",
      message: expect.stringContaining("Invalid IRI"),
    });
    expect(await readFile(outputPath, "utf8")).toBe("previous verified target");
  },
);

test("public writer configuration works through the verified publication boundary", async () => {
  const directory = await mkdtemp(join(tmpdir(), "uo-writer-configuration-"));
  directories.push(directory);
  const manager = OWLManager.createOWLOntologyManager();
  const ontology = await manager.loadOntologyFromOntologyDocument(
    new StringDocumentSource(
      "Ontology(<https://example.test/configured> Declaration(Class(<https://example.test/ConfiguredClass>)))",
      { format: OWLDocumentFormats.FUNCTIONAL },
    ),
  );
  const outputPath = join(directory, "configured.owl");
  const publish = () =>
    writeVerifiedOntology({
      ontology,
      manager,
      outputPath,
      format: OWLDocumentFormats.RDF_XML,
    });
  await publish();
  const defaults = await readFile(outputPath, "utf8");
  manager.setOntologyWriterConfiguration(new OWLOntologyWriterConfiguration());
  await publish();
  expect(await readFile(outputPath, "utf8")).toBe(defaults);
  manager.setOntologyWriterConfiguration(
    new OWLOntologyWriterConfiguration()
      .withIndentSize(2)
      .withBannersEnabled(false),
  );
  await publish();
  const configured = await readFile(outputPath, "utf8");
  expect(defaults).toMatch(/^ {4}<owl:Class /mu);
  expect(defaults).toContain("<!--");
  expect(configured).toMatch(/^ {2}<owl:Class /mu);
  expect(configured).not.toContain("// Classes");
  expect(configured).not.toContain("<!-- https://example.test/ConfiguredClass");
  expect(configured).toContain("<!-- Generated by @hadden-industries/owlapi");
  expect(configured).toContain(
    'rdf:about="https://example.test/ConfiguredClass"',
  );
});
